src/api.cpp
Without this we would crash when trying to flush the event or breadcrumbs on disabled SDKs.
=> feat: Do not fail on disabled DSN on flush

.vscode/c_cpp_properties.json, include/sentry.h, premake/premake5.sentry.lua, src/backends/breakpad.cpp, src/backends/breakpad.hpp, src/backends/crashpad.cpp, src/backends/crashpad.hpp, src/modulefinders/base.cpp, src/modulefinders/base.hpp, src/modulefinders/darwin.cpp, src/modulefinders/darwin.hpp, src/options.cpp, src/options.hpp, src/scope.cpp, src/uuid.cpp, src/value.cpp, src/value.hpp
This adds support for module finders (darwin only at the moment)
=> feat: initial support for module finders

Makefile
...so we can test crashing with segfault inside the container.
=> fix: Run unconfined Docker container in dev

src/modulefinders/darwin_modulefinder.cpp
=> feat: Ignore system error on lock

src/transports/winhttp_transport.cpp
=> Add a fallback on WinHttpOpen

src/dsn.cpp, src/url.hpp, tests/unittests/test_dsn.cpp
This implements the canonical dsn format that we want to put into the envelope header.
=> feat: Added canonical dsn serialization to dsn

src/backends/inproc_backend.cpp
This adds a mechanism for the event payload when the event is made in the inproc signal handler.
=> feat: Add mechanism for crashes from the signal handler

src/modulefinders/linux_modulefinder.cpp
Thanks @mitsuhiko for helping troubleshooting this at 23:00 your time :)
=> fix: endinness on android

src/backends/crashpad_backend.cpp
=> feat: Handle not being able to open the event file

src/api.cpp
=> fix: Flush scopes at least once

src/path.cpp
This should help debugging #84
=> feat: Log failures in directory creation

include/sentry.h, src/backends/crashpad_backend.cpp, src/options.cpp, src/options.hpp
=> feat(api): Add an option to enable the system crash reporter

src/backends/crashpad_backend.cpp, src/path.hpp
=> feat: Always create breadcrumb files

.gitignore, CMakeLists.txt, examples/example.c, src/backends/sentry_inproc_backend.c, src/sentry_core.c, src/sentry_core.h, src/sentry_envelope.c, src/sentry_envelope.h, src/sentry_path.h, src/sentry_string.c, src/sentry_string.h, src/sentry_utils.c, src/sentry_value.c, src/transports/sentry_disk_transport.c, src/transports/sentry_disk_transport.h, src/transports/sentry_libcurl_transport.c, src/unix/sentry_unix_path.c, src/windows/sentry_windows_path.c
… and enforce it inside the signal handler to write crashes to disk
=> feat(transport): Implement a disk transport

azure-pipelines.yml, src/linux/sentry_procmaps_modulefinder.c
this should compile down to api16
=> feat: Use custom code to get the linux vdso

CMakeLists.txt, Makefile, azure-pipelines.yml, scripts/bump-version.sh
And also avoid building all the tests and examples by default
=> build: Add option for static library builds

src/sentry_value.c
=> fix: Fix invalid memory access when resizing a sentry_value

.gitignore, CHANGELOG.md, CMakeLists.txt, README.md
And also make installing via cmake work correctly
=> docs: Update the README for c-version changes

src/sentry_scope.c, src/sentry_scope.h, tests/test_integration.py
Adds SDK version to the scope:
=> feat: Add sdk information to scope

Makefile, leak-suppressions.txt, src/backends/sentry_crashpad_backend.cpp
Updates leak tests and fixes a leak in the crashpad backend.
=> fix: Memory leaks

CMakeLists.txt
=> cmake: add SENTRY_PIC option

src/modulefinder/sentry_modulefinder_linux.c, src/path/sentry_path_unix.c, src/sentry_random.c
=> fix: Clean up read loops and errno handling

CHANGELOG.md, README.md, include/sentry.h, tests/assertions.py, tests/test_integration_http.py
Still waiting for the other PRs…
=> release: 0.2.3

src/backends/sentry_backend_crashpad.cpp
=> feat: Bump to latest crashpad version

src/modulefinder/sentry_modulefinder_apple.c
=> fix: Correct typedef on 32bit Apple platforms

CMakeLists.txt, examples/example.c, include/sentry.h, src/sentry_core.c, src/sentry_options.c, src/sentry_options.h, src/sentry_scope.c, src/sentry_scope.h, src/sentry_symbolizer.h, tests/assertions.py, tests/unit/CMakeLists.txt
This is technically a regression from 0.1, which used to do this.
=> feat: Symbolize Stacktraces in-process

src/backends/sentry_backend_breakpad.cpp, src/backends/sentry_backend_crashpad.cpp, src/backends/sentry_backend_inproc.c, src/sentry_backend.h, src/sentry_core.c, src/sentry_transport.c, src/sentry_transport.h, src/transports/sentry_transport_curl.c, src/transports/sentry_transport_winhttp.c
=> ref: Pass options and run explicitly

CHANGELOG.md, README.md, examples/example.c, include/sentry.h, src/sentry_core.c, src/sentry_options.c, src/sentry_options.h, tests/unit/test_attachments.c, tests/unit/test_session.c
This also updates the changelog and documentation.
=> feat: Stabilize sessions and enable by default

.github/ISSUE_TEMPLATE/bug_report.md, CHANGELOG.md, CMakeLists.txt
=> fix: Bump Windows CMake requirement

src/sentry_value.c
Not really sure if we need to care about https://en.wikipedia.org/wiki/X86-64#Canonical_form_addresses ?
=> fix: Fix NaN-tagging of pointers and document things

src/sentry_sync.c
Small fix for Windows XP, without it you will get compilation error for XP target.
Windows XP is not main target platform, so I think it is OK to not have thread naming on it.
=> fix: disable thread name setting for windows XP target

src/sentry_sync.c, tests/unit/test_path.c
=> fix: Fix building on MinGW

src/sentry_json.c
=> fix: Switch wrong cast in printf check

include/sentry.h, src/sentry_core.c
This is a rebase of #388, ready to be merged.
=> feat: Add sentry_reinstall_backend API

CHANGELOG.md, README.md
=> docs: Clean up the README a bit and draft Changelog

.github/workflows/release.yml, scripts/bump-version.sh
Switches the release process to the centralized release action. Craft is run directly on the host.
=> ci(gha): Switch to release workflow

CHANGELOG.md, include/sentry.h, src/sentry_core.c, src/sentry_options.c, src/sentry_options.h
=> feat: Add ability to control the max_breadcrumbs

CMakeLists.txt, src/unwinder/sentry_unwinder_libunwindstack.cpp
This updates the `libunwindstack` unwinder that is used on android.
Based on https://github.com/getsentry/libunwindstack-ndk/pull/3
=> ref: Update Android Unwinder

src/sentry_utils.c
=> fix: Use atomics for locale initialization

.github/workflows/ci.yml, tests/cmake.py
Updates the crashpad module to bring in the fixes for cross-compilation / universal build on macOS.
=> fix: macOS universal build (crashpad update)

CMakeLists.txt, README.md
=> fix: Further clean up platform libraries for static linking

src/sentry_utils.c, tests/unit/test_utils.c
=> fix: Avoid double-free on invalid DSN

src/transports/sentry_disk_transport.c, src/transports/sentry_function_transport.c, tests/unit/main.c, tests/unit/sentry_testsupport.h, tests/unit/test_attachments.c, tests/unit/test_basic.c
Simple PR to fix Unity builds (CMAKE_UNITY_BUILD).
=> Fix Unity builds

src/sentry_sync.c
I was a bit overeager merging #570, and it broke master. It seems like on linux the unlock is very quick and ends the thread immediately, doing the `detach` later leaks the thread.
=> fix: Properly close the background worker thread on timeout

CMakeLists.txt
=> Increments CXX standard to 14 to allow crashpad build

tests/test_build_static.py
This pulls in https://github.com/getsentry/breakpad/pull/24.
=> meta: Bump breakpad

external/CMakeLists.txt
=> ios should not compile exception_handler.cc

CONTRIBUTING.md
=> chore: list the libraries required to run tests

CMakeLists.txt
=> meta: Update break/crashpad to 2022-04-12 (NATIVE-506)

src/CMakeLists.txt
This fixes #701
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>
=> Fix library-only build with no examples.

CHANGELOG.md
=> chore: Update changelog for release

CHANGELOG.md
=> chore: Update changelog with community contributions

CHANGELOG.md, src/backends/sentry_backend_inproc.c
=> feat: disable PC adjustment in the backend for libunwindstack

README.md
=> Update README.md remove beta note

README.md
=> fix: conan-badge link in README.md

README.md
=> Add docs link to readme

CHANGELOG.md
see: https://github.com/getsentry/libunwindstack-ndk/pull/8
=> chore: update libunwindstack 2023-09-13

README.md
=> docs: reflect Linux default backend in README.md

scripts/git-precommit-hook.sh
After deleting a file, precommit hook fails because it tries to to format non-existent files.
=> chore: precommit hook must not check deleted or renamed files

CHANGELOG.md
=> rectify changelog link and formatting

.github/workflows/ci.yml, ndk/Makefile, ndk/lib/CMakeLists.txt, ndk/lib/api/sentry-native-ndk.api, ndk/lib/build.gradle.kts, ndk/lib/src/androidTest/java/io/sentry/ndk/SentryNdkTest.java, ndk/lib/src/androidTest/java/io/sentry/ndk/sample/NdkSample.java, ndk/lib/src/androidTest/jni/ndk-test.cpp, ndk/lib/src/main/java/io/sentry/ndk/NdkOptions.java, ndk/lib/src/test/java/io/sentry/ndk/NdkOptionsTest.java, ndk/sample/build.gradle.kts, ndk/sample/src/main/java/io/sentry/ndk/sample/MainActivity.java
sidequest to be merged into https://github.com/getsentry/sentry-native/pull/1176
=> add NDK testing setup

CHANGELOG.md
=> chore: clean-up CHANGELOG.md pre-release

CONTRIBUTING.md, Makefile, README.md
Explain the benchmark scenarios, add a link to https://getsentry.github.io/sentry-native/ + instructions for running locally.
=> docs: add benchmark sections to README.md & CONTRIBUTING.md

CHANGELOG.md
=> chore: pre-release changelog fixes.

README.md
=> chore: add github ci and codecov badges to readme

README.md
Also, fix the failing link for nixpkgs.
=> chore: add homebrew package shield

CHANGELOG.md, CONTRIBUTING.md, scripts/run_tests.ps1
I never got around to opening this for other Windows users.
=> docs: windows test and formatter runners

CHANGELOG.md, include/sentry.h
=> meta: identify Xbox as a separate SDK name

CHANGELOG.md
=> chore: prepare changelog for a patch release

tests/unit/test_path.c
=> chore: disable mtime tests on switch

.github/workflows/ci.yml, examples/example.c, scripts/install-llvm-mingw.ps1, src/sentry_logs.c, src/sentry_value.c, tests/test_integration_http.py
This should fix the cause of the failing Win32 CI job (which only stably reproduced there, but was a general ownership problem in the log construction of the current implementation affecting all platforms).
(This is a fix branch to a feature branch)
=> fix ownership issues in single buffer batching

CHANGELOG.md, src/sentry_logs.c
Fixes https://github.com/getsentry/sentry-native/issues/1400
Part of https://github.com/getsentry/sentry-native/issues/1398
=> fix: add proper sdk name to logs
