getsentry/sentry-native

.gitignore

We'd like to ignore the new files generated by setting up and building sentrypad out of the box.

ignore cloned crashpad and in-source visual studio cruft

---

premake/premake5.lua

Notably using the Win32 and x64 platform names to workaround this
premake problem:
https://github.com/premake/premake-core/issues/1171

Build both 32-bit & 64-bit versions of the SDK

---

premake/premake5.crashpad.lua

This stops the command window from being shown when it is executed.

Build crashpad_handler as a "Windows" application

---

include/sentry.h
src/api.cpp
src/options.cpp
src/scope.cpp
src/scope.hpp
src/value.cpp
src/value.hpp
tests/test_api.cpp
tests/testutils.hpp

This PR adds separate tests for most of the API and fixes a few bugs along the way:
- **NEW**: Add `sentry_set_context` and `sentry_remove_context` as per unified API spec
- **FIX**: Uninitialized backend in the standalone build
- **FIX**: `tags`, and `extra` not merged due to a bug in `merge_key`
- **FIX**: Internal `const` qualifiers on the `Value` C++ API
- **TEST**: Initialize with DSN to ensure that the SDK is in active mode

fix: Add tests and fix various bugs

---

.vscode/c_cpp_properties.json
premake/premake5.crashpad.lua
premake/premake5.sentry.lua

Fixes include paths in libsentry_breakpad and removes redundant rules for crashpad utils.

build: Fix build configs for crashpad and breakpad

---

premake/premake5.crashpad.lua

Updates Crashpad upstream to https://github.com/getsentry/crashpad/commit/2fb4e9e6a4328ed49b15eec0a848fcc646208840.

build: Update crashpad and fix zlib build on Windows

---

src/api.cpp
src/backends/crashpad_backend.cpp
src/scope.cpp
src/scope.hpp
src/value.cpp

Contains various smaller fixes for issues mostly occurring on Windows:
- Fix in the JSON serializer to properly escape backslashes in strings
- Open files msgpack files in binary mode to avoid escaping of newlines
- Reduce lock time for `set_fingerprint`
- Do not serialize modules or stack frames for minidump event supplements
- Simplify msgpack write logic slightly

fix: Apply small fixes

---

premake/premake5.crashpad.lua

When building with enabled Safe SEH on Windows x86, linking failed with the following error:
```
error LNK2026: module unsafe for SAFESEH image
```
This is due to a missing compile flag to `cl` when building MASM modules for crashpad_util. Crashpad sets this by adding `/safeseh` to ASM options. In premake, this is possible by setting `exceptionhandling 'SEH'` on ASM files for the Win32 platform. It took me a little to find the correct filter, but now it generates this in the VS project XML (which builds fine):
```
<Masm Include="..\crashpad\build\crashpad\util\misc\capture_context_win.asm">
<UseSafeExceptionHandlers Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">true</UseSafeExceptionHandlers>
<UseSafeExceptionHandlers …
```

build(win32): Fix SafeSEH build on Win32

---

Makefile
include/sentry.h
src/api.cpp
src/options.cpp
src/transports/function_transport.cpp
src/transports/function_transport.hpp
src/value.cpp
src/value.hpp
tests/test_values.cpp
tests/testutils.hpp
tests/unittests/test_value.cpp

This exposes the envelopes to the C layer and changes the way we handle memory on the C layer.
The tests showed we used memory management already incorrectly around our own API and from the user's perspective it's nicer for lookups in structures to return borrowed values instead of owned ones. This now removes `sentry_value_free` and instead adds `sentry_value_incref` and `senty_value_decref`.
I removed `free` so that people upgrading are more likely to run into memory management issues. They were already required to call free so all they need to do now is to remove that call most likely and potentially call incref if they keep the value around.

feat: Expose envelopes to C and change refcounting semantics

---

src/uuid.cpp

On my emulator that's the only reliable way to get a UUID without pulling in lots of deps.

fix(android): Fix UUIDv4 generation on android

---

include/sentry.h
src/modulefinders/darwin_modulefinder.cpp
src/modulefinders/linux_modulefinder.cpp
src/modulefinders/windows_modulefinder.cpp
src/scope.cpp
src/value.cpp
src/value.hpp
tests/test_api.cpp
tests/unittests/test_value.cpp

This adds support for freezing values (makes them immutable). This should help avoid situations
where code wants to modify shared values in the event struct.
This also adds an internal mutex to the value so we don't crash on concurrent modifications.

feat: Add support for value freezing to avoid changing shared values

---

src/transports/libcurl_transport.cpp

fix: Use CURLOPT_CAINFO to specify path to CA bundle

---

src/backends/crashpad_backend.cpp

Disables the system crash reporter. This is only relevant on macOS, where the system handler takes substantial time after crashpad has finished writing a minidump. It leads to delays, which are generally unwanted.

ref(crashpad): Disable the system crash handler

---

include/sentry.h
src/api.cpp
src/backends/base_backend.hpp
src/backends/crashpad_backend.cpp
src/backends/crashpad_backend.hpp
src/io.cpp
src/io.hpp
src/options.cpp
src/options.hpp
src/transports/libcurl_transport.cpp
src/transports/winhttp_transport.cpp
tests/test_consent.cpp
tests/unittests/test_io.cpp

This adds user consent tracking for uploads.  Currently this is only
reflected in the crashpad backend.

feat: Add user consent tracking

---

CMakeLists.txt
examples/example.c

The DSN is hardcoded for now, as it is not yet fetched via ENV by default

build(example): add cmake target for example and add DSN

---

CMakeLists.txt
examples/example.c
src/sentry_core.c
src/sentry_transport.c
src/sentry_transport.h
src/transports/sentry_libcurl_transport.c

Hook up the curl transport as a default, and fix a deadlock when sending events
With this changes, submitting an event is actually possible

feat(transport): hook up the curl transport

---

azure-pipelines.yml
scripts/start-android.sh

So far, 18 is the lowest we can go. We would need to find an alternative to `getauxval` to get to 16.

ci: Test on android API 18

---

CMakeLists.txt

Context: https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md#additional-required-arguments
Fixes sentry-android-ndk build on Windows.

replacing build-id to sha1 as uuid is not Windows friendly

---

CMakeLists.txt
src/path/sentry_path_windows.c

- add ability to setup target windows version
- fix compatibility with Windows 7 (`PathCchRemoveFileSpec` appeared only in Windows 8.0)

build: respect CMAKE_SYSTEM_VERSION

---

examples/example.c
src/backends/sentry_backend_breakpad.cpp
src/backends/sentry_backend_inproc.c
src/sentry_sync.c
src/sentry_sync.h
src/sentry_transport.h
src/transports/sentry_transport_curl.c
src/transports/sentry_transport_none.c
src/transports/sentry_transport_winhttp.c
tests/conditions.py
tests/test_integration_crashpad.py
tests/test_integration_http.py
tests/test_integration_stdout.py

The inproc and breakpad backends will invoke the default transports dump method,
that method will first check that it is actually the transport responsible,
and will then dump all the envelopes in matching tasks.
The bg worker is changed in a way that it only pops tasks *after* they are completed.
That way, in case of a race, we end up with duplicate events rather than dropped events.

feat: Dump in-flight requests in case of a crash

---

CMakeLists.txt

cmake: detect if sentry is main project

---

src/backends/sentry_backend_breakpad.cpp
src/backends/sentry_backend_inproc.c
src/sentry_database.c
src/sentry_database.h
tests/assertions.py
tests/test_integration_stdout.py

After some discussion with @marandaneto, I think this is useful to have even outside of `sentry-android`.
Please note that `sentry-native` will never read, or delete the file, it is for outside observers only.

feat: Write crash timestamp into a marker file

---

.clang-format
src/sentry_random.c
src/sentry_utils.h

The SENTRY_CTOR isn't working for me and afaik it is not safe to call LoadLibraryA outside of main() ie during static initialization or DLLMain. Switching this to initialize on the first call to random instead.

Fixes initializing random on windows

---

include/sentry.h
src/backends/sentry_backend_breakpad.cpp
src/backends/sentry_backend_crashpad.cpp
src/backends/sentry_backend_inproc.c
src/sentry_backend.h
src/sentry_core.c

Allows manually triggering of the backend given a completed ucontext

Handle Exception API

---

CMakeLists.txt

Without this, we get the following linker error:
```
make: Entering directory '.../build'
SOLINK_MODULE(target) Debug/obj.target/addon.node
/usr/bin/ld: .../lib/linux/libsentry.a(sentry_core.c.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
addon.target.mk:211: recipe for target 'Debug/obj.target/addon.node' failed
make: *** [Debug/obj.target/addon.node] Error 1
make: Leaving directory '.../build'
```

build: add -fPIC flag when building static lib on Linux

---

CMakeLists.txt
sentry-config.cmake.in
tests/__init__.py
tests/conftest.py

This pr is in tandem with https://github.com/getsentry/crashpad/pull/7
Should make #205 unnecessary
Fixes #204 
I've changed the crashpad submodule to my repo to let CI succeed (🤞)
I'll remove it once https://github.com/getsentry/crashpad/pull/7 gets merged.

build(cmake): Use crashpad targets

---

azure-pipelines.yml
include/sentry.h
src/sentry_core.c

fixes #213
Also make `sentry_options_get_http_proxy` const-correct, fixes #214

fix: Expose a method to clear the module cache

---

src/backends/sentry_backend_breakpad.cpp
src/backends/sentry_backend_inproc.c

fix: Add an explicit log when crashes have been captured

---

src/path/sentry_path_unix.c
src/path/sentry_path_windows.c
src/sentry_core.c
src/sentry_path.h

This way, sentry is resilient to cwd changes, as mentioned in #220.

fix: Use absolute paths for the database

---

src/path/sentry_path_windows.c

Complementary to https://github.com/getsentry/crashpad/pull/11. My latest build attempt http://zonme.to2x.ovh:8090/job/sentry-native/job/master/9/console also highlighted a missing header reference.

[MinGW] Missing errno.h

---

src/modulefinder/sentry_modulefinder_linux.c

This is the only place I can think of that could potentially segfault. The only thing that is still accessed directly though is the vdso.

fix: Avoid reading procmaps memory offsets directly

---

examples/example.c
src/backends/sentry_backend_breakpad.cpp
src/modulefinder/sentry_modulefinder_linux.c
src/sentry_envelope.c
src/sentry_utils.c
src/sentry_utils.h
tests/__init__.py
tests/assertions.py
tests/test_integration_http.py
tests/unit/test_utils.c

Lesson learned: Don’t merge code without e2e tests ;-)
Also, I’m very much tempted to just rip out all the endpoint and multipart-related code and just send envelopes *always*. As it is now, regular `capture_event` works with non-relay servers still.
One question I have: A crashed session won’t increase the `errors` count. Is that expected?

fix: Send sessions as envelopes to the correct endpoint

---

src/backends/sentry_backend_crashpad.cpp

I no longer remember why this was disabled in the first place, but it seems that this is a relic from old times. Tested on Windows 10, and it uploaded just fine like this.

fix(crashpad): Enable GZIP uploads

---

src/modulefinder/sentry_modulefinder_linux.c

Basically the same as https://github.com/getsentry/sentry-rust/issues/220, but we haven’t hit the case in native yet.

fix: Pad short code_ids with 0

---

src/sentry_unix_pageallocator.c

```
2020-06-01 17:27:33 /build/contrib/sentry-native/src/sentry_unix_pageallocator.c:63:24: error: use of undeclared identifier 'page_size_'
2020-06-01 17:27:33     __msan_unpoison(a, page_size_ * num_pages);
2020-06-01 17:27:33                        ^
2020-06-01 17:27:33 /build/contrib/sentry-native/src/sentry_unix_pageallocator.c:63:21: error: use of undeclared identifier 'a'
2020-06-01 17:27:33     __msan_unpoison(a, page_size_ * num_pages);
2020-06-01 17:27:33                     ^
2020-06-01 17:27:33 2 errors generated.
```

Fix the undeclared identifiers under msan

---

src/sentry_session.c
src/sentry_session.h
tests/test_integration_stdout.py

The session now owns its `release`/`environment`, to avoid borrowing problems when loading from disk. And also add a test that ensures loading from disk and flagging as abnormal works.

fix: Avoid memory unsafety when loading session from disk

---

src/sentry_json.c
src/sentry_sync.c

I ran gcc with `-fanalyzer`, which uncovered some potential null dereferences. 
It does however have some false positives as well, such as:
https://github.com/getsentry/sentry-native/blob/b48c21d244092658d6e2d1bb243b705fd968b9f7/src/sentry_envelope.c#L90
Plus it complains about some code in `mpack` which we vendor.

fix: Two issues uncovered by GCC analyzer

---

include/sentry.h
src/CMakeLists.txt
src/sentry_core.h
src/sentry_logger.c
src/sentry_logger.h
src/sentry_options.c
src/sentry_options.h

add ability to create logger hook
```c
void logger_hook(sentry_level_t level, const char* message, va_list args)
{
char buf[1024]{};
vsprintf(buf, message, args);
OutputDebugStringA(buf);
}
...
void init_sentry() 
{
sentry_options_t* _options = sentry_options_new();
sentry_options_set_logger(_options, logger_hook);
...
}
```
fixes #148 
references #244

feat: implement logger hook

---

src/backends/sentry_backend_crashpad.cpp
src/sentry_logger.c

Otherwise we would end up with an empty event file.
fixes #208

fix: Flush scope immediately when starting Crashpad Backend

---

CMakeLists.txt
README.md
tests/unit/CMakeLists.txt

Allows to build sentry-native with the static runtime using MSVC compiler.
Fixes #282 
```
mkdir build
cd build
cmake .. -DSENTRY_BUILD_RUNTIMESTATIC=ON
cmake --build .
```

feat: add SENTRY_BUILD_RUNTIMESTATIC flag

---

CMakeLists.txt
README.md

These options are undesirable in the case when the binary is intended to `dlopen` third-party `.so` files (in our case ODBC drivers) and hide its symbols from them. Exposing symbols lead to segfaults when there's a collision between binary and library symbols.

Add cmake option to disable exposing symbols

---

src/unwinder/sentry_unwinder_dbghelp.c

The ContextRecord parameter should be a PCONTEXT (not a PCONTEXT* as was coded)
A local copy of context made as StackWalk64 can alter it.

ContextRecord incorrectly passed to StackWalk64

---

src/sentry_logger.c

strncat works incorrectly when string is not filled with `\0`
In result:
* expected: `[sentry] DEBUG starting transport`
* actual result: `[sentry] ННННННННННННННННННННННННННээээDEBUG starting transport`

fix: fix log output on Windows

---

src/sentry_logger.c
src/sentry_logger.h

The usage of `strcat` bothers gcc-10 and clang analyzer.
fixes #298

fix: Avoid using strncat and a trailing newline in logs

---

src/sentry_core.c
src/sentry_options.h
src/sentry_ratelimiter.c
src/sentry_sync.c
src/sentry_utils.h
src/transports/sentry_transport_winhttp.c
tests/__init__.py
tests/unit/test_ratelimiter.c

Adds a new `sentry__monotonic_time` util which is used for timeouts, and works around connection delays on windows due to `localhost` resolving to ipv6 by default.

fix: Use monotonic time for timeouts

---

src/sentry_core.c
src/sentry_logger.c
src/sentry_logger.h

fix: Start logger as early as possible

---

azure-pipelines.yml
src/sentry_logger.c
tests/__init__.py
tests/conftest.py

* run `scan-build` (clang analyzer) on linux (although currently it only produces warnings and not hard errors)
* switch to gcc-10 and clang-10 on linux
* run asan leak-check on clang builds on linux

ci: Run analyzers and leak-check on CI

---

src/sentry_logger.c
tests/test_integration_crashpad.py
tests/test_integration_http.py
tests/test_integration_ratelimits.py

This also turns on the logger for the HTTP-based tests.
Fixes #309

fix: Avoid invalid memory access in the logger

---

tests/test_integration_crashpad.py

Adds basic integration tests for the crashpad backed.
Originally submitted by @Swatinem in https://github.com/getsentry/sentry-native/pull/310

test(integration): Add tests for crashpad

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/pull_request_template.md
CONTRIBUTING.md
Makefile
README.md
azure-pipelines.yml

* Creates a contribution guide, which documents the testing infrastructure and options.
* Adds issue/PR templates, which ask for relevant versions/options, and instruct contributors to run tests.
* Configures CI to not run for every push ;-)

meta: Add Contribution guide and issue/pr templates

---

CHANGELOG.md
examples/example.c
include/sentry.h
src/sentry_options.c
src/sentry_options.h
tests/unit/test_attachments.c

This is now unused with the latest crashpad changes.

ref: Remove name parameter from sentry_options_add_attachment

---

.codecov.yml

This changes to PR comment to only update after all reports are in, and only include a short diff.
Also changes the github status to be informational only (without gating commits), and disables the `patch` status.

meta: Make codecov less annoying

---

.gitignore

ignore only root build folders as there are needed build folders in dependencies

meta: gitignore only root build folders

---

.clang-format
CHANGELOG.md
include/sentry.h
src/backends/sentry_backend_breakpad.cpp
src/backends/sentry_backend_crashpad.cpp
src/backends/sentry_backend_inproc.c
src/sentry_core.c
src/sentry_core.h
src/sentry_database.c
src/sentry_envelope.c
src/sentry_options.c
src/sentry_options.h
src/sentry_scope.c
src/sentry_session.c
src/sentry_session.h
src/sentry_sync.h
src/sentry_transport.c
src/sentry_transport.h
src/sentry_utils.c
src/sentry_utils.h
src/transports/sentry_transport_curl.c
src/transports/sentry_transport_winhttp.c
tests/assertions.py
tests/test_integration_crashpad.py
tests/test_integration_http.py
tests/unit/test_attachments.c
tests/unit/test_envelopes.c
tests/unit/test_logger.c
tests/unit/test_utils.c

Wraps all accesses of the global objects object in a lock. This also changes the DSN to be a heap allocated and refcounted type, since the http workers need to separately own a reference.
fixes #280

fix: Lock global options whenever they are accessed

---

src/sentry_database.c

Fixes crash in case if sentry is not able to restore session from .json file
That's funny that sentry is able to log crash in its internals :)

fix: nullptr dereferencing in sentry__process_old_runs()

---

src/backends/sentry_backend_breakpad.cpp
src/backends/sentry_backend_crashpad.cpp
src/backends/sentry_backend_inproc.c
src/sentry_backend.h
src/sentry_core.c
src/sentry_database.c
src/sentry_database.h
tests/__init__.py
tests/cmake.py
tests/leaks.txt
tests/test_integration_crashpad.py

This uses crashpads `SetFirstChanceExceptionHandler` on Linux,
and an additional exception filter on Windows, and a heuristic on macOS.

fix: Flush session and send queue in crashpad backend

---

README.md
examples/example.c
include/sentry.h

I think `XDG_CACHE_HOME` fits the usecase the best, as this is *non-essential* data and can be removed at any time without any real negative effects (apart from missing abnormal/crashed sessions). Not sure about user consent though.
closes #355 CC @sseyod how do you like the explanation?

docs: Better document the database-path requirements

---

CHANGELOG.md
include/sentry.h
src/sentry_ratelimiter.c
tests/unit/test_ratelimiter.c

fixes #361 
looks like another change slipped through that I forgot to commit in https://github.com/getsentry/sentry-native/commit/2fed9755d351334ea366e3390dacbd9ff7666df9

fix: Parse rate limits with multiple categories

---

src/sentry_value.c
tests/unit/test_value.c

There is already this note here about `sentry_value_t`:
https://github.com/getsentry/sentry-native/blob/425b803d53acc2d598633fd64ac969508487007e/include/sentry.h#L127-L128
I think in a future version we can just typedef this to a `uint64_t`.
This now moves double values to a heap allocation with a refcount.

fix: Change NaN-boxing to Pointer Tagging

---

external/CMakeLists.txt

Discovered a problem with building breakpad backend on windows:
This is from my small [demo](https://github.com/variar/qt_cpp_sentry/runs/1195358380?check_suite_focus=true)
```
[38/46] Building CXX object external\sentry-native\external\CMakeFiles\breakpad_client.dir\breakpad\src\client\windows\handler\exception_handler.cc.obj
FAILED: external/sentry-native/external/CMakeFiles/breakpad_client.dir/breakpad/src/client/windows/handler/exception_handler.cc.obj 
C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x64\cl.exe  /nologo /TP -D_UNICODE -Igenerated -I..\external\sentry-native\external\breakpad\src -I..\external\sentry-native\external /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /Zi /O2 /Ob1 /DNDEBUG -std:c++14 /showIncludes …
```

Define UNICODE for Breakpad build

---

src/backends/sentry_backend_inproc.c

Not quite sure if we should do this in the backend, or rather patch the unwinder itself…
fixes #384

fix: Unwind from local stack if ucontext fails

---

src/backends/sentry_backend_inproc.c
src/sentry_json.c
tests/unit/test_value.c

`EXCEPTION_ACCESS_VIOLATION` is defined as `0xC0000005`, which overflows
an i32 and will turn negative, which causes processing problems later on.
This is a simpler alternative to #385 as it just uses a double for the signal number, and makes sure doubles are printed to json in full fidelity.

fix: Use doubles to represent signal numbers

---

CMakeLists.txt
README.md

Adds `SENTRY_BUILD_SHARED_LIBS` cmake option
It allows to set different library type for sentry than for other libraries when sentry-native is used as a subdirectory.

feat: add SENTRY_BUILD_SHARED_LIBS build options

---

README.md

Updates documentation to mention the minimum supported onpremise version. This constraint comes from using the Envelope endpoint, which has first been introduced via Relay into 20.6.0.

fix(doc): Mention minimum supported Sentry version

---

include/sentry.h
src/sentry_utils.c
tests/unit/test_utils.c

In https://github.com/getsentry/relay/pull/822, we added more diagnostics to log invalid payloads sent by SDKs. The Native SDK does not send a `sentry_client` identifier when using the minidump endpoint, which is relevant for debugging invalid msgpack payloads sent through the crashpad handler.
This adds the `sentry_client` query parameter to the minidump URL which is then passed to crashpad. For envelope and old-style store requests, this had been part of the auth header.

fix(crashpad): Send sentry_client with all crashpad requests

---

src/sentry_sync.c
src/sentry_sync.h

This fixes an error reported by Windows Application Verifier.

fix: Explicitly free lock objects

---

include/sentry.h
src/sentry_options.c
src/sentry_options.h
src/sentry_sync.c
src/sentry_sync.h
src/transports/sentry_transport_curl.c
src/transports/sentry_transport_winhttp.c

Add "Sentry BgWorker" description to the Sentry background worker thread.
Fixes #411 
---
Fun fact: in Windows, Thread Handle != Thread Id.
But in sentry-native, `sentry_threadid_t` is actually thread handle, not id :)

feat: name sentry background worker thread

---

examples/example.c
src/backends/sentry_backend_crashpad.cpp
src/sentry_backend.h
src/sentry_core.c
tests/assertions.py
tests/test_integration_crashpad.py

This way crashes that happen after shutdown can still get the correct scope
and breadcrumb info when using crashpad

fix: Retain run folder on shutdown

---

CMakeLists.txt
examples/example.c
src/path/sentry_path_windows.c
tests/unit/CMakeLists.txt

This warning was newly introduced in VS 16.8, but breaks with the
Windows SDKs own `winbase.h` header. We will just suppress it for now.

fix: Update crashpad and suppress C5105

---

.github/workflows/ci.yml
src/path/sentry_path_windows.c
tests/cmake.py
tests/test_integration_http.py

Current `master` CI is failing because:
* CodeChecker added another dependency that is not installed. We now pin codechecker and make sure the needed dependency is there.
Plus some minor oneliners that slipped through.

ci: Pin CodeChecker version and fix Linux dependencies

---

CMakeLists.txt

Installs PDB files if sentry is being compiled by MSVC.
fixes #440 
references #439

feat: install PDB files

---

CMakeLists.txt
README.md
src/CMakeLists.txt
src/integrations/sentry_integration_qt.cpp
src/integrations/sentry_integration_qt.h
src/sentry_core.c

The integration turns Qt logging via e.g. qDebug() into breadcrumbs.
Enable the integration by passing -DSENTRY_INTEGRATION_QT=ON during
configure time. This will add a runtime dependency on the QtCore
library to sentry.

Add minimal Qt integration

---

CMakeLists.txt

* expose sentry-native version to CMake project, fixes #460 
* expose sentry-native version to CMake package, it allows things like
CMakeLists.txt
```
...
find_package(sentry 0.4.5)
...
```
CMake output
```
CMake Warning at CMakeLists.txt:4 (find_package):
Could not find a configuration file for package "sentry" that is compatible with requested version "0.4.5".
The following configuration files were considered but not accepted:
D:/Projects/VCS/github/getsentry.sentry-native/~install/lib/cmake/sentry/sentry-config.cmake, version: 0.4.4
```

feat: expose sentry-native version to CMake project and package

---

src/sentry_scope.c

The objects on the scope are mutable, which means they can re-allocate at any time.
This could potentially lead to segfaults when concurrently serializing an event object
that has a reference to such a scope object.
Now we shallowly clone those objects into the event which should guarantee they do not
move.
CC @daxpedda

fix: Clone mutable scope data when applying to event

---

include/sentry.h

Just found a small typo :wink:.

Fix typo in `sentry_options_get_max_breadcrumbs`.

---

CMakeLists.txt
README.md

Fixes possible issues with static sentry-native library.
References https://github.com/getsentry/sentry-native/issues/477

feat: cleanup platform libraries linkage

---

src/sentry_utils.h

Fixes #454. 'Should have made that pull request a long time ago !

Fix MinGW / Clang 'missing-field-initializers' warning

---

src/path/sentry_path_windows.c

Fix: Free intermediate allocation in Windows path functions

---

src/sentry_sync.c
src/sentry_sync.h

- Correctly initialize non-static Mutex
- Correctly Close Thread Handle
fixes #491

fix: Resolve some ApplicationVerified Issues on Windows

---

src/sentry_database.c
src/sentry_envelope.c
src/sentry_json.c
src/sentry_json.h
src/sentry_value.c
src/sentry_value.h

Refactors the jsonwriter a bit, taking an existing stringwrite where possible to avoid intermediate allocations.

ref: Optimize jsonwriter to allocate less in some cases

---

src/modulefinder/sentry_modulefinder_linux.c

Fixes errors about missing type `elf_aux_entry`
Tested on ppc64le (POWER9).

Fix building on ppc64 and ppc64le

---

src/sentry_sync.c
src/sentry_sync.h
tests/__init__.py

It seems pthreads are cleaned up in `join`, except when they are
`detached`, in which case they clean up after themselves.

fix: Use valgrind correctly and fix a leak

---

src/sentry_utils.c
src/sentry_value.c
src/transports/sentry_transport_curl.c

Check the return value in more places, and handle errors better.
Also, explicitly null-terminate in more places as some implementations
might not be well behaved.

fix: Tighten up a few snprintf usages

---

tests/unit/CMakeLists.txt
tests/unit/fuzz.c

Doing the same as in #428.
The Windows Compiler suddenly started tripping over its own SDK headers after a CI update.

fix: Windows SDK Compiler Warning

---

tests/cmake.py

It looks like cmake is broken and builds ALL the targets when the parallel option is specified first, lol

build: Avoid building all targets

---

README.md
include/sentry.h
src/backends/sentry_backend_crashpad.cpp

feat: Invoke before_send hook when using Crashpad

---

examples/example.c
include/sentry.h
src/backends/sentry_backend_inproc.c
src/sentry_value.c
tests/assertions.py
tests/test_integration_http.py

Adds:
* `sentry_value_new_exception`
* `sentry_value_new_thread`
* `sentry_value_new_stacktrace`
* `sentry_event_value_add_exception`
* `sentry_event_value_add_thread`
Deprecates `sentry_event_value_add_stacktrace`
Fixes #235
Fixes #376
Fixes #503

feat: Add more Event Payload convenience methods

---

README.md
examples/example.c
include/sentry.h
src/sentry_core.c
tests/unit/test_attachments.c
tests/unit/test_basic.c
tests/unit/test_consent.c
tests/unit/test_envelopes.c
tests/unit/test_logger.c
tests/unit/test_session.c
tests/unit/test_uninit.c

This replaces the former `sentry_shutdown`, which is being forwarded.
Fixes #474

feat: Introduce `sentry_close`

---

CHANGELOG.md

The crashpad update should fix:
* fixes #374
* fixes #504

meta: Prepare Changelog for upcoming release

---

src/backends/sentry_backend_crashpad.cpp
src/sentry_backend.h
src/sentry_core.c
src/sentry_core.h
src/sentry_scope.c
src/sentry_scope.h
tests/unit/test_mpack.c

ref: Pass options to scope apply directly

---

CHANGELOG.md
src/sentry_boot.h
src/sentry_utils.c
src/sentry_utils.h
src/unwinder/sentry_unwinder_libbacktrace.c

This should allow building on older macOS versions as well as
running on older versions by fixing the usage of __builtin_available,
and adding a different clock source for older macOS versions.
Fixes #495
Fixes #497
Hopefully also fixes #228

fix: Better macOS availability checks

---

Makefile

Updated Makefile to fix problems with test generation and generation of the Python virtual environment.

fix: Update venv and test-discovery Makefile targets

---

examples/example.c
src/backends/sentry_backend_crashpad.cpp
src/backends/sentry_backend_inproc.c
src/sentry_session.c
tests/requirements.txt
tests/test_integration_crashpad.py
tests/test_integration_http.py

Previously, the `inproc` and `crashpad` (on linux) backends didn’t correctly reset their signal handlers when doing `reinstall_backend` (or multiple `init` calls for that matter).
This has led to an infinite loop generating crashes.
The fix now correctly unregisters the inproc/crashpad signal handlers, and adds an integration test using `reinstall_backend` to make sure we do not end up in an infinite loop.
(this includes/supercedes #547)

fix: Avoid recursion when using `sentry_reinstall_backend`

---

src/modulefinder/sentry_modulefinder_linux.h
src/sentry_core.c
src/sentry_envelope.c
src/sentry_envelope.h
src/sentry_ratelimiter.c
src/sentry_ratelimiter.h
src/sentry_unix_pageallocator.c
src/sentry_unix_pageallocator.h

This matches other defines present in code already

fix: Address -Wundef warning for SENTRY_UNITTEST defines

---

src/modulefinder/sentry_modulefinder_apple.c

We have received a report that the `sentry_get_modules_list` on mac can deadlock
when other code concurrently does a `dlopen` and thus invokes the `add_image`
callback from a different thread.
We shorten/split the locked blocks in order to avoid holding a lock in the
`get_modules` function whenever the `add_image` function is being invoked possibly
from other threads.

fix: Shorten/Split Locked sections to avoid deadlock

---

.github/workflows/ci.yml
src/modulefinder/sentry_modulefinder_linux.c
src/unwinder/sentry_unwinder_libunwindstack.cpp

This is using the `process_vm_read` call to safely poke at random memory. It also makes sure to shim the libc provided call with a direct syscall for older Android devices.
Waiting for https://github.com/getsentry/libunwindstack-ndk/pull/4

fix: Make Linux modulefinder/unwinder safer

---

include/sentry.h

Clarifies the unwind-related docs a bit, see #562

docs: Try to better explain unwind API

---

src/backends/sentry_backend_crashpad.cpp
src/sentry_backend.h
src/sentry_core.c
src/sentry_value.c
tests/unit/test_value.c

fix: Make Crashpad Backend respect max_breadcrumbs setting

---

src/sentry_sync.c
src/transports/sentry_transport_winhttp.c

This is essentially https://github.com/getsentry/sentry-native/pull/568 with a proper fix to continue dumping queued envelopes.
CC @smibe

fix: Cancel slow winhttp requests on shutdown

---

include/sentry.h
src/sentry_core.c
src/sentry_options.c
src/sentry_options.h

made shutdown timer customizable

---

CMakeLists.txt

Should remove the need for this vcpkg port patch: https://github.com/microsoft/vcpkg/blob/5f32a49551c6101d294c7e73806999abab806570/ports/sentry-native/fix-libcurl.patch
As well as fix some edge-case linking scenarios.
On CMake < 3.12, where `CURL::libcurl` is not defined, it will use the prior code.

CMake: Link to the CURL::libcurl target when available

---

CHANGELOG.md

Pick up this required fix for mingw: https://github.com/getsentry/crashpad/commit/7a31c8491ec771d7f7577c63585e2c4c4d49c03c

meta: Update crashpad to 2021-07-14

---

CMakeLists.txt
tests/unit/CMakeLists.txt

I noticed that building
```cmd
cmake -S . -B build -D BUILD_SHARED_LIBS=[ON/OFF] -D SENTRY_BACKEND=crashpad -D SENTRY_BUILD_RUNTIMESTATIC=ON -G ninja
ninja -C build
```
was failing on Windows with errors exactly like in #357 -- I was curious to see the cause of the regression, so I bisected until I found the offending PR #502. I guess in my previous setup and in most people's tests, we set `-D SENTRY_BUILD_TESTS=OFF` and therefore never run into this!
This PR adds the relevant fix to `tests/unit/CMakeLists.txt` to fix the error from #357. I'm not at all familiar with your testing setup, but I'd really recommend setting up a regression test for this.
And to anyone who is running into this, again, the workaround is to set `-D SENTRY_BUILD_TESTS=OFF`.

Fix `SENTRY_BUILD_RUNTIMESTATIC` for `sentry_fuzz_json` unit test

---

.github/workflows/ci.yml

It looks like codechecker's using a node feature (node-fibers) that is no longer supported on the version of node on our ubuntu image. I've used the workaround suggested in https://github.com/Ericsson/codechecker/issues/3353. It doesn't look like it should have a negative impact on our runs in CI as I would assume that it shouldn't care for UI builds by design, but I could be misinterpreting the flag.

ci(codechecker): Workaround for code checker not building due to node issues

---

include/sentry.h
src/sentry_options.c
src/sentry_options.h

This adds basic config values to sentry options that will be used by performance monitoring. The traces sampler is deliberately omitted from this due to its complexity.

feat(tracing): Add config options

---

CHANGELOG.md

The changelog had an entry under the wrong heading.

fix: Correct changelog entry

---

.github/workflows/ci.yml

tl;dr fix macos ci
We're using `macos-latest` in our integration tests, which has recently been bumped up from 10.15 to ~11.6 (see https://github.com/actions/virtual-environments/issues/4060 and reported operating system in https://github.com/getsentry/sentry-native/actions/runs/1575459945 after the bump was pushed).
Thankfully, the only thing that appears to have broken are our integration tests because of a versioning quirk. Python's `platform.mac_ver()` is reporting that it's on version 10.16 which is a backwards-compatible version number that represents Big Sur. Something else is using the non-backwards compatible version number with the major version bumped up to 11, causing an unintentional mismatch. More on this can be found in …

ci: Make integration tests capable of reading the non-backwards compatible version number for Big Sur

---

src/sentry_core.c
src/sentry_core.h

Does what it says on the tin. There are a few places that need to know this, so pull this out into a helper to avoid duplicating logic. This isn't `static` because it does get used in a different file later.
relates to #601

feat(tracing): Introduce a helper that identifies events that are transactions

---

include/sentry.h
src/sentry_core.c
src/sentry_core.h

Transactions will want to piggyback on most of what the original `sentry_capture_event` already does, but this means that it'll be possible to pass in transactions in to that function. This deliberately prevents users from being able to inadvertently finish transactions with this function.
relates to #601

feat(tracing): Restrict `sentry_capture_event` so it only sends non-transaction events

---

CMakeLists.txt
examples/example.c
include/sentry.h
src/CMakeLists.txt
src/sentry_core.c
src/sentry_core.h
src/sentry_envelope.c
src/sentry_envelope.h
src/sentry_options.c
src/sentry_options.h
src/sentry_scope.c
src/sentry_scope.h
src/sentry_tracing.c
src/sentry_tracing.h
src/sentry_uuid.c
src/sentry_uuid.h
src/sentry_value.c
tests/unit/CMakeLists.txt
tests/unit/sentry_testsupport.h

This moves both the external and the internal parts of the API related to performance monitoring (/tracing) behind a compile flag. This is to make it easier for us to iterate on the API, and to potentially break it or leave it in a compilable but incomplete state. 
If an end user runs into any issues with the feature they must have deliberately opted into the feature and/or attempted to use something that isn't publicly documented and is therefore not yet publicly supported by the SDK yet.
relates to #601

feat(tracing): Move all performance monitoring code behind a compile flag

---

tests/unit/test_tracing.c

Retroactively applies some macros created in previous PRs to the rest of the tracing test suite. No functional changes.
I'm strongly considering splitting the test file into two, one dedicated to transaction testing and another to testing spans. Would love thoughts or feedback on this idea.
related to #601 
picks up off of #636

feat(tracing): Retroactive unit test improvements

---

src/sentry_core.c

Missed copying over a property from the transaction context into the transaction when starting the latter.

fix(tracing): Actually set the operation on a transaction

---

src/modulefinder/sentry_modulefinder_linux.c

Avoids a potential segfault reading the section names, and also falls back when
vm_readv lacks permissions.
Should fix #578

fix: Read section names safely

---

src/modulefinder/sentry_modulefinder_linux.c
src/modulefinder/sentry_modulefinder_linux.h

This goes a bit further than #641 and brings back mmap-ing modules in such a way that it still works with libraries loaded from apk on Android.

fix: Revert to mmap-ing modules in the modulefinder

---

include/sentry.h
src/sentry_core.c
tests/unit/test_uninit.c

This adjusts `sentry_set_transaction` and `sentry_remove_transaction` so that if `SENTRY_PERFORMANCE_MONITORING` is defined, they also change the name of/remove the transaction ("`span`") attached to the scope.

ref(tracing): Update name of attached transaction in set_transaction [NATIVE-444]

---

CMakeLists.txt

Fixes #661.
We do not need case-insensitive check here because `SENTRY_LIBRARY_TYPE` is not intended to be set by user.

fix: cmake `SENTRY_LIBRARY_TYPE` variable check

---

src/sentry_os.c

We were previously relying on the `kernel32.dll` version, as does
Crashpad. However that version can lag behind OS releases, which can
manifest itself as failing integration tests, as the version does not
match the one returned from python `platform.version()`.
CC @Mixaill as you suggested this back in https://github.com/getsentry/sentry-native/pull/467#pullrequestreview-578269776

fix: Read Windows Version from Registry

---

src/sentry_ratelimiter.c
src/sentry_ratelimiter.h
src/transports/sentry_transport_curl.c
src/transports/sentry_transport_winhttp.c
tests/test_integration_ratelimits.py

The transport will now fall back to a default 60 second rate limit
when it receives a 429 response without additional headers.

fix: Apply default rate limit

---

examples/example.c
include/sentry.h
src/sentry_core.c
tests/unit/test_tracing.c

This also renames `sentry_start_transaction` to use the naming that is defined here: https://develop.sentry.dev/sdk/performance/#static-api-changes

ref: Make API forward-compatible to Sampling Context (NATIVE-457)

---

examples/example.c
include/sentry.h
src/sentry_core.c
tests/unit/test_tracing.c

This reverts the name change of `sentry_transaction_start` to `sentry_start_transaction` for reasons detailed in https://github.com/getsentry/sentry-native/pull/663#issuecomment-1018067869.

ref(tracing): Revert name change of sentry_transaction_start

---

include/sentry.h
src/sentry_core.c
src/sentry_scope.c
src/sentry_scope.h
src/sentry_tracing.c
src/sentry_tracing.h
tests/unit/test_tracing.c

Currently the native SDK only supports attaching a transaction to a scope, but it's supposed to be a transaction or a span. This PR changes the `sentry_set_span` function to take a `sentry_span_t` and adds a `sentry_set_transaction_object` that does the same for `sentry_transaction_t`. Internally, a scope now keeps two pointers, one to a transaction and one to a span, and setting one of them unsets the other.

feat(tracing): Allow setting a scope on a span

---

src/sentry_options.c
tests/unit/test_tracing.c

This fixes a minor issue that forces the user to explicitly set `max_spans` in sentry options in order to be able to capture any spans. Now, the default amount of max spans (1000) is automatically set if the user enables tracing. 
Custom `max_spans` values will be preserved if a user enables and disables tracing prior to initializing sentry. 
e.g. if the following actions are performed in this order:
- set max spans to 500
- set a sampling rate >0
- set a sampling value <= 0
- set a sampling rate >0
- init sentry
sentry will enforce a limit of a 500 max spans.

fix(tracing): Set max spans to the default amount when tracing is enabled

---

tests/__init__.py
tests/assertions.py
tests/test_integration_http.py

This adds an integration test which inspects the envelope of a
transaction sent by the native SDK.
-------

test: Add integration test for envelope with transaction

---

CHANGELOG.md
src/sentry_scope.c

fix: Correctly apply contexts from the scope

---

include/sentry.h
tests/assertions.py

Is this a feasible solution to this issue? https://github.com/getsentry/sentry-java/issues/1901
That assumes we can define `SENTRY_SDK_NAME` in the NDK [CMakeLists](https://github.com/getsentry/sentry-java/blob/main/sentry-android-ndk/CMakeLists.txt#L8) or [Gradle](https://github.com/getsentry/sentry-java/blob/33aeeb081e38aac8da02fd4101b6dfeb25d424ce/sentry-android-ndk/build.gradle.kts#L31-L32)

allow defining `SENTRY_SDK_NAME` externally

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
tests/requirements.txt

black is currently causing our CI to fail. A naive bump up to a version that fixes this shouldn't be high risk for us since: a. it's a code formatter and b. we use python for our integration tests.
The tests don't completely pass but I don't believe it's a hard requirement to at least get this change in. Some of the tests are failing for completely unrelated reasons (deprecated windows environments on GitHub) and can/should be fixed in a separate PR just to keep things compartmentalized.

ref: Update black so it stops breaking our CI

---

CHANGELOG.md

meta: Update changelog for release

---

CHANGELOG.md
src/backends/sentry_backend_crashpad.cpp
src/sentry_backend.h
src/sentry_core.c

It seems that the defaults in the crashpad_handler only trigger after a long 10min delay, and let the db grow to up to 128M by default. We generally do not care about older/completed reports at all, so make sure to aggressively prune them.

feat: More aggressively prune the Crashpad database

---

CONTRIBUTING.md
examples/example.c
include/sentry.h
src/sentry_options.c
tests/test_integration_crashpad.py

Fixes https://github.com/getsentry/sentry-native/issues/705
* Instead of modifying any existing interfaces, I just added new API functions for `sentry_options_t`
* I am not sure if we need all the functions, but most of the options interface is symmetric (i.e. getters and setters) so I did the same, but still tried to hide the backend behind the API facade
* Added new option to example code to allow it to run in an integration-test

feat: Allow disabling of the crash-handler backend at runtime.

---

CHANGELOG.md
external/CMakeLists.txt

The crashpad upstream still needs to be merged into our fork.

deps: Update Break/Crashpad to 2022-06-14

---

.github/workflows/ci.yml
CHANGELOG.md
CONTRIBUTING.md
examples/example.c
include/sentry.h
src/backends/sentry_backend_breakpad.cpp
src/backends/sentry_backend_crashpad.cpp
src/backends/sentry_backend_inproc.c
src/sentry_core.c
src/sentry_core.h
tests/assertions.py
tests/test_integration_crashpad.py
tests/test_integration_stdout.py

* mentioned in the header docs `before_send` vs `on_crash` behavior
* adapted `sentry__prepare_event` to provide a flag for backends on
whether `before_send` should be invoked
* adapted backends to prevent running `before_send` even if `on_crash`
returns true
* added `on_crash` vs `before_send` integration tests for `inproc` and
`breakpad` (`crashpad` will follow)
* removed `stdbool.h` from `sentry.h` and replaced return value `bool`
with `int` in `sentry_crash_function_t` (since `bool` seemed to be
explicitly prevented in the header up to now)
* added remaining CHANGELOG entries for upcoming release

ref(on_crash): follow-up to make on_crash releasable

---

src/backends/sentry_backend_crashpad.cpp

@Swatinem: This was a minor left-over from yesterday's (#734)  merge. This way we signal more clearly to whoever is supervising on windows (ie. the same as the wrapping handler would).

ref: terminate from crashpad handler with sensible return code.

---

src/modulefinder/sentry_modulefinder_windows.c

Turns out a PE file can have more than one debug directory entry.
We now iterate over all of them, trying to find the one that has a valid
CodeView record that we can use to get a debug_id from.
Crashpad does the same here, for reference:
https://chromium.googlesource.com/crashpad/crashpad/+/refs/heads/main/snapshot/win/pe_image_reader.cc#162

fix: Iterate all debug directory entries

---

.github/workflows/ci.yml
CHANGELOG.md
tests/cmake.py

- bumps Linux CI host to Ubuntu 22.04
- bumps new gcc to 12, clang to 14
- bumps Android API/NDK to latest versions
- renames CI jobs so their names are version independent (for easier updating)

ci: Bump compiler and OS versions

---

.github/workflows/danger.yml

Add a CI workflow to apply common checks to PRs, e.g. check if a changelog entry is missing.

ci: add danger workflow

---

CHANGELOG.md

synced with commit
235e2604e2fa3c1f8f7a68c5e285f9622e741e64
of upstream repo:
https://android.googlesource.com/platform/system/unwinding
here:
https://github.com/getsentry/libunwindstack-ndk/pull/6

chore: update libunwindstack-ndk submodule

---

CHANGELOG.md
src/transports/sentry_transport_winhttp.c

This seems to have been a typo all along.
Fixes #762

fix: Do not shut down winhttp transport on flush

---

.github/workflows/ci.yml
CHANGELOG.md
src/modulefinder/sentry_modulefinder_linux.c

For some reason the Native SDK only searched in the ELF program headers for a code-/build-id entry, after which if unsuccessful, it immediately fell back to generating a code-/build-id on the fly by hashing the first page of ".text" section.
This change also searches for a ".note.gnu.build-id" section, after searching the program headers was unsuccessful.

Search code-id in ".note" ELF sections

---

CHANGELOG.md
src/transports/sentry_transport_curl.c

Up to now, we have only printed the numeric error code returned by `curl_easy_perform()`, which isn't sensationally helpful to our users.
We now also print the contents of a `CURLOPT_ERRORBUFFER` and fall back to `curl_easy_strerror()` in case the error buffer is empty.
Fixes https://github.com/getsentry/sentry-native/issues/774

fix: better error messages in `sentry_transport_curl`

---

CHANGELOG.md
src/transports/sentry_transport_curl.c

The company that I work for is using an internal proxy with in-house generated public keys, which can be up to 400 characters long. When substituting the Sentry public key with the custom one, the `curl` transport doesn't write the `X-Sentry-Auth` header because the existing buffer 255 is too small.

fix: increase curl headers buffer size to 512

---

CHANGELOG.md
src/sentry_sync.c

Specifically on Windows, the `sentry_thread_spawn` macro is defined as follows:
```
(*ThreadId = CreateThread(NULL, 0, Func, Data, 0, NULL),               \
*ThreadId == INVALID_HANDLE_VALUE ? 1 : 0)
```
We can see that `ThreadId` is initialized with the value returned by `CreateThread`, but the new thread might be running before `CreateThread` returns. If the new thread tries to access `bgw->thread_id`, the value might not be initialized yet, leading to undefined behaviour / crash.
In this change a new function `sentry__thread_get_current_threadid` is added, which returns the current thread id in a reliable way.

fix: avoid race condition when starting bgw thread

---

.github/workflows/ci.yml
CHANGELOG.md
src/path/sentry_path_unix.c
src/sentry_database.c

For some reason, the file lock on UNIX was always opened using `O_RDONLY`. This doesn't make sense in combination with `O_TRUNC` since it is a write operation. On some systems (the trigger scenario was AWS EFS), this will lead to an `EBADF` if we try to `flock()` that descriptor. The docs consider this combination undefined.
This change also removes the AIX compile-conditional since this should work on all systems now.
I also added a warning to the run-initialization in case we get an error when trying to lock.

fix: open the file lock on "UNIX" with O_RDRW

---

CHANGELOG.md

Cleanup pre-release changelog

---

external/CMakeLists.txt

Breakpad now uses features from C++17: https://chromium-review.googlesource.com/c/breakpad/breakpad/+/3954471
We should make this explicit via the `breakpad_client` target requirements. This change only creates a lower bound because for compilers that support only parts of C++17, the build will not necessarily complain. For instance, `breakpad` uses `static_assert()` without a second message parameter, which was added with https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3928.pdf, which not all compilers will support that accept the C++17 standard (e.g., GCC only supports it starting from version 6).
The issue was initially raised here: https://github.com/getsentry/sentry-native/discussions/798#discussioncomment-4826165
CC: @markushi, @bitsandfoxes

fix: explicit breakpad C++17 dependency

---

CHANGELOG.md
include/sentry.h
src/sentry_session.c
src/sentry_session.h
tests/unit/test_session.c

As of right now, the status code of the session cannot be modified through this SDK. This is a problem when errors or crashes are handled manually. Such sessions are then marked as "crash-free". This is especially problematic when the `on_crash` callback is used, which may discard processing the event further. This is a snippet from the `inproc` backend:
https://github.com/getsentry/sentry-native/blob/19df84a7b437a9dbe2dabd2a451ac2cf508e00dd/src/backends/sentry_backend_inproc.c#L531-L556
_This is the only place where the session may be marked with the crashed status code._
Because of these reasons, I propose making the session status a part of the public API and an option to end the session using that custom status code. Another possibility is making the session structure public like in …

feat: Allow ending a session with a different status code

---

CHANGELOG.md
src/backends/sentry_backend_crashpad.cpp
src/sentry_sync.h
src/unwinder/sentry_unwinder_dbghelp.c

This change helps fix mingw builds (together with: https://github.com/getsentry/crashpad/pull/78)

Fixes for mingw builds (+ ARM64)

---

CHANGELOG.md

Fixes https://github.com/getsentry/sentry-native/issues/744
Fixes https://github.com/getsentry/sentry-native/issues/773

chore: sync with recent crashpad changes

---

.github/workflows/ci.yml
CHANGELOG.md
scripts/install-llvm-mingw.ps1
tests/cmake.py

Add llvm-mingw CI pass.
Depends on:

[CI] Add llvm-mingw

---

include/sentry.h
src/sentry_core.c
src/sentry_info.c
src/sentry_scope.c
src/sentry_scope.h
src/sentry_sync.c
src/sentry_utils.c

This is one of many aspects where C and C++ standards deviate:
An empty parameter list in C++ is equivalent to a void parameter list. But in C an empty parameter list meant: you can give any number of any types as parameters (ignoring the difference between declaration and definition for brevity).
With C11, this "feature" became obsolete: empty parameter lists are no longer standard-conforming C. Since some of those are in our API surface we should fix this.

fix: use void for all empty parameter-lists in C functions

---

CHANGELOG.md
CMakeLists.txt
src/exports.map
tests/unit/CMakeLists.txt

Trying to implement the suggestion from https://github.com/getsentry/sentry-android/issues/509
CC @eakoli and @blinkov since you added that CMake setting.
I’m thinking if we should maybe expose the breakpad and crashpad symbols? Maybe users might expect to be able to call out to crashpad if they link to sentry built with the crashpad backend.

fix: Add a linker script to enforce exported symbols

---

CHANGELOG.md

https://github.com/getsentry/crashpad/pull/81

fix: Remove OpenSSL dependency for the crashpad backend on Linux

---

CHANGELOG.md
README.md

Since your project is available on the [conan center](https://conan.io/center/sentry-native), what about advertizing it on the README.md ?

Add conan badge

---

CHANGELOG.md
src/backends/sentry_backend_crashpad.cpp

Since no one commented on my suggestion here: https://github.com/getsentry/sentry-native/pull/840#issuecomment-1540586984, here is the PR that implements that :P

feat: inspect/enrich event in crashpad backend

---

CHANGELOG.md
src/backends/sentry_backend_crashpad.cpp

fixes #788 together with https://github.com/getsentry/crashpad/pull/86

feat: crashpad handler http-proxy support

---

CHANGELOG.md
CMakeLists.txt

same as https://github.com/getsentry/crashpad/pull/85

Fix compiler error with msvc on non-unicode system

---

.gitignore

As suggested on Discord. It makes sense to have this similar to the build clause.

chore: add top-level install directories to gitignore

---

CHANGELOG.md
src/backends/sentry_backend_breakpad.cpp
src/backends/sentry_backend_crashpad.cpp

So the story goes like this:
An Unreal crash report lands in relay but the `crash_reason` got ignored and asserts and ensures ended up with the severity `FATAL`. 
Relay [now](https://github.com/getsentry/relay/pull/1677/files) reads the reason from the Unreal context and sets the level appropriately.
Unfortunately, Sentry simply overwrite the level set in Relay with `FATAL` anyway. With [this PR](https://github.com/getsentry/sentry/pull/50717/files), previously set levels get respected.
This PR aims to initialize crash events with `FATAL` but still allow users to overwrite the level.

fix: Setting the default level for crash events in Crashpad to `fatal`

---

.github/workflows/ci.yml
tests/assertions.py
tests/requirements.txt
tests/test_integration_http.py
tests/test_integration_stdout.py

This is a follow-up to https://github.com/getsentry/sentry-native/pull/852

test: assert crash-level fatal in integration tests

---

CHANGELOG.md
include/sentry.h

This PR
- clarifies that sentry_shutdown does not remove any crash handlers
Copying over a conversation from the Sentry discord;
> supervacuus — Today at 4:25 AM
@sappho
The crashpad client does not provide a mechanism to uninstall its in-process crash-handler nor shutdown the crashpad_handler executable. So the handler is still installed after sentry_close().
> On Linux we brutally restore signal handlers without making crashpad aware of this. Maybe we should do the same on Windows?
> If you want to disable the crash-handler you can call  SetUnhandledExceptionFilter(NULL) which will disable the local handler installed by crashpad. This can happen in your Shutdown() method right after invoking sentry_close(). 
More TODO involving

docs: clarify behavior of sentry_flush + sentry_close

---

CHANGELOG.md
scripts/install-llvm-mingw.ps1
src/sentry_sync.c

This will also fix: https://github.com/getsentry/sentry-native/issues/882
But I am mostly trying to get a cross-check from the CI because I have some weird behavior when reinstalling the crashpad backend on Windows (this is not ready for review).

chore: update crashpad 2023 09 28

---

CHANGELOG.md

This also breaks CI and thus prevents the release of 0.6.7 which should contain https://github.com/getsentry/sentry-native/pull/901

fix: stuck crashpad_client on windows

---

CHANGELOG.md
src/backends/sentry_backend_inproc.c

I am creating this as a tracking branch for a pre-release. Disabling "our" `sigaltstack` on Android is probably not the solution that will end up in a release, but it should provide a sound basis for broader testing in the downstream SDKs.

fix: disable sigaltstack on Android

---

.github/workflows/ci.yml
scripts/start-android.sh

For some reason, in the recent config of the Android emulator or the available Android system images on the macOS-runner image, the property `sys.boot_completed` no longer appears.
However, the emulator is attached as a device and can run our tests (which all execute in the Android shell rather than requiring a specific UI state).
While it might be interesting to figure out why `sys.boot_completed` no longer appears, in my tests, `wait-for-device` __and__ executing a shell command was a sufficient boot condition for the emulator to run our tests afterward.

ci: change emulator boot-condition for android tests

---

CHANGELOG.md
src/backends/sentry_backend_crashpad.cpp

This PR is related to this issue: https://github.com/getsentry/sentry-native/issues/900#issuecomment-1825457223.
The crashpad client is stateful (on macOS, it contains the send right to the exception port), and it might be a good idea to keep the client instance for the life cycle of the Native SDK. This also fixes part of the issue (terminating one `crashpad_handler` kills the other). I don't see any downside to this, although having a second client will almost always overwrite a previously initialized one.

fix: Maintain client in crashpad state

---

CHANGELOG.md

This fixes https://github.com/getsentry/sentry-native/issues/907 + includes the [ARM64 build fix](https://github.com/getsentry/crashpad/pull/90) from @compnerd.
I also updated and tested this in the context of https://github.com/getsentry/sentry-native/issues/900 to verify that the observed behavior wasn't a temporary regression.

chore: update crashpad 2023-11-24

---

CHANGELOG.md

https://github.com/getsentry/crashpad/pull/90
https://github.com/getsentry/crashpad/pull/92
https://github.com/getsentry/crashpad/pull/93
https://github.com/getsentry/crashpad/pull/94

fix: crashpad build for Windows on ARM64

---

CHANGELOG.md
src/sentry_core.c
tests/unit/test_consent.c

Do not do early exit loop early, that leads to a incorrect reference counting of options during consent setting.

Remove options memory leak during consent setting

---

CHANGELOG.md
CMakeLists.txt
README.md

We've been discussing this for a year now, and it is a recurring and understandable mental burden for newcomers (as well as developers of integrations within Sentry). From my POV, there is no reason to have `breakpad` over `crashpad` as the default backend for Linux besides the worry that we might break builds that rely on that default. Most recent interactions with new users show that people choose `crashpad` in the end anyway.
I would make this a breaking change toward 0.7.0.
This is also related to the context touched by https://github.com/getsentry/sentry-native/issues/908.
I am open to counter-arguments.

build: make crashpad the default backend on Linux

---

CHANGELOG.md
examples/example.c
tests/assertions.py

A [conversation on Discord](https://discord.com/channels/621778831602221064/1206628673080528957) made clear, that we have no example of how to create `data` properties in breadcrumbs using the `value` API in the Native SDK. This PR rectifies this by adding the `data` properties of an `http` [breadcrumb](https://develop.sentry.dev/sdk/event-payloads/breadcrumbs/#breadcrumb-types) and asserts on the new data in the integration tests.

docs: provide example for breadcrumb data property

---

README.md

related: https://github.com/getsentry/sentry-docs/pull/9164

chore: add note about experimental state of standalone SDK

---

.github/workflows/ci.yml
tests/assertions.py
tests/requirements.txt

After fixing the failing mingw build in #964, we have another failing build caused by an update to the runner image. We can't connect to the pytest-httpserver anymore, but seemingly only in the clang-asan/llvm-cov build.

fix: failing clang-asan/llvm-cov tests

---

include/sentry.h
tests/test_unit.py

A race in one of our unit tests was uncovered, probably due to recent fixes and updates in our `ASAN` runner config (https://github.com/getsentry/sentry-native/pull/965), which may have influenced the timing. 
The `custom_logger` test was written for a single-threaded configuration, but since it was automatically added to the transport test suite, the logger in this test would also be called from multiple threads, now leading to unexpected sequences in its assertions:
* https://github.com/getsentry/sentry-native/actions/runs/8388482978/job/22972769285#step:12:5003
* https://github.com/getsentry/sentry-native/actions/runs/8379423984/job/22947434351#step:12:4997
* https://github.com/getsentry/sentry-native/actions/runs/8379423984/job/22946299495#step:12:5038
The fix for this is a trivial …

fix: exclude custom_logger from transport test-suite

---

CHANGELOG.md
src/modulefinder/sentry_modulefinder_linux.c

-resolves https://github.com/getsentry/sentry-native/issues/971
* `make format` ran -> there are files outside of this PR that need modification
* `make test` ran -> `316 passed, 8 skipped, 1 warning in 73.93s (0:01:13)`

RISC-V support

---

CHANGELOG.md
tests/assertions.py

Fixes https://github.com/getsentry/sentry-native/issues/955 via https://github.com/getsentry/relay/pull/3225 and https://github.com/getsentry/crashpad/pull/98

feat: enable automatic MIME detection for crashpad attachments.

---

CHANGELOG.md

Fixes: https://github.com/getsentry/sentry-native/issues/975.
Actual change: https://github.com/getsentry/crashpad/pull/99.

fix: allow crashpad to run with Epic's Anti-Cheat client.

---

CHANGELOG.md
examples/example.c
src/sentry_tracing.c
tests/assertions.py
tests/test_integration_http.py
tests/unit/test_tracing.c

fixes https://github.com/getsentry/sentry-native/issues/983
This aligns with the current implementations in sentry-java, sentry-dotnet, and sentry-cocoa (and probably others). The [RFC 0101](https://github.com/getsentry/rfcs/blob/main/text/0101-revamping-the-sdk-performance-api.md) mentions the issue as one of its drivers. In the meantime we should allow transactions to serialize `data` where it doesn't get discarded.

fix: store transaction `data` in event `extra`

---

CHANGELOG.md
CMakeLists.txt
CONTRIBUTING.md
examples/example.c
src/backends/sentry_backend_breakpad.cpp
src/backends/sentry_backend_crashpad.cpp
src/backends/sentry_backend_inproc.c
src/sentry_os.c
src/sentry_os.h
tests/assertions.py
tests/test_integration_crashpad.py
tests/test_integration_stdout.py

Currently, stack overflows on Windows die somewhere in the handler because we run out of stack space. This is the first attempt to fix the situation by reserving stack space before it is exhausted. This is an analog to `sigaltstack()` on Linux, but Windows only provides a "reserved amount" interface, and with that, you have fewer options to shoot yourself in the foot.
Fixes #987.
Fixes #977.

fix: correctly support stack overflows across platforms

---

.github/workflows/ci.yml

The last release https://github.com/getsentry/sentry-native/releases/tag/0.7.3 should have had a maven artifact (`./ndk/lib/build/distributions/sentry-native-ndk-0.7.2.zip`) file attached to it, but the regex was simply wrong 🙈 

Fix path to ndk module

---

.craft.yml

Only the source bundle should be uploaded to GCS, and only the NDK bundle should be uploaded to maven.

Ensure the proper artifacts are uploaded to gcs/maven

---

CHANGELOG.md
src/backends/sentry_backend_crashpad.cpp
src/sentry_core.c
src/sentry_database.c
src/sentry_envelope.c
src/sentry_json.c
src/sentry_json.h
src/sentry_session.c
src/sentry_session.h
src/sentry_tracing.c
src/sentry_utils.c
src/sentry_utils.h
src/sentry_value.c
tests/unit/test_utils.c

This partially approaches #941 but is helpful for other scenarios.

feat: change the timestamp resolution to microseconds

---

.github/workflows/ci.yml
.github/workflows/release.yml

see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
In our case, this only affects the following:
* actions/checkout (v3 -> v4)
* actions/setup-python (v4 -> v5)
* codecov/codecov-action (some previously "approved" sha-pin -> v4)
The last time I updated, some tool blocked the change due to `codecov` getting an unbounded major version assigned, which seemingly is only allowed for `actions/*`- and `getsentry/*`-actions. I hope this time it works since `codecov` is now a sentry product 😅.

ci: update GHA deps to non-deprecated versions

---

CHANGELOG.md
ndk/lib/build.gradle.kts

With the JNI move we switched from using the static stdlib to `c++_shared`.  This had the side effect of `libc++_shared.so` being integrated into the build artifact. As the version of `libc++_shared.so` is tied to the version of the NDK, this could cause troubles / undefined behavior if customer is using a different NDK version than us.

Use static STL, hide it from prefab

---

CHANGELOG.md
scripts/install-llvm-mingw.ps1

Fixes: #1002.
Actual change: [getsentry/crashpad#/101](https://github.com/getsentry/crashpad/pull/101).

fix: crashpad build for Windows ARM64 via LLVM-MINGW

---

.github/workflows/ci.yml
CHANGELOG.md
src/backends/sentry_backend_breakpad.cpp
tests/cmake.py
tests/leaks.txt

The sentry-native companion to https://github.com/getsentry/crashpad/pull/105

chore: Update crashpad to 2024-06-11

---

CHANGELOG.md
src/backends/sentry_backend_crashpad.cpp
tests/assertions.py
tests/test_integration_crashpad.py
vendor/mpack.c
vendor/mpack.h

This change cleans up a couple of issues in the current crashpad backend:
* Via scope-flushing, we use `mpack` in the signal handler, which uses system malloc. This change configures mpack to use `sentry_malloc`, which switches to the page-allocator inside the signal handler. Fixes #687.
* We flush the scope outside the crash handler and then again inside. This is only necessary on macOS and on Windows when a crash gets handled vie the WER module. There is no need to flush the scope into `__sentry_event` outside the handler on Linux.
* The scope-flushing unnecessarily introduced a shared mutable variable between the two paths (via `crashpad_backend_flush_scope` and the signal handler), which could be called from two different threads. We can ensure that these two paths handle separate …

fix: crashpad scope flushing synchronization

---

CHANGELOG.md
src/path/sentry_path_unix.c
src/path/sentry_path_windows.c
src/sentry_database.c
src/sentry_envelope.c
src/sentry_json.c
src/sentry_json.h
src/sentry_path.h
src/sentry_value.c
tests/unit/fuzz.c
tests/unit/test_fuzzfailures.c
tests/unit/test_value.c

Partially fixes https://github.com/getsentry/sentry-native/issues/1001

feat: stream envelope directly to file

---

.github/workflows/ci.yml

Additionally, bump `codecov-action` to 4.5.0
Fixes #1023.

ci: introduce codecov token

---

CHANGELOG.md
CMakeLists.txt
ndk/lib/CMakeLists.txt
ndk/lib/build.gradle.kts
ndk/sample/CMakeLists.txt
ndk/sample/build.gradle.kts

This fixes #989.
I tried to reach the most minimal version I could successfully deploy to a 16kb page-size image on the emulator.
Important here:
* NDK 27 is required because the toolchain dependencies must also be compiled for 16kb page sizes. That's why I explicitly configured this
* appended new linker settings to all CMake library targets
* enable legacy packaging because we want to stay compatible with `AGP <= 8.2`: https://developer.android.com/guide/practices/page-sizes#agp_version_82_or_lower
Open topics:

feat: support 16kb page size on Android 15

---

CHANGELOG.md
src/sentry_utils.h

The timestamp resolution was changed to microseconds in https://github.com/getsentry/sentry-native/pull/995. However, this has never correctly worked on Windows because `SYSTEMTIME`, a return value from the underlying call to `GetSystemTime()`, contains only milliseconds, not microseconds: https://learn.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-systemtime.
Instead, `GetSystemTimeAsFileTime()` can be used as its return value "contains a 64-bit value representing the number of 100-nanosecond intervals". This also helps in reducing two API calls to just one.

fix: timestamp resolution to microseconds on Windows

---

scripts/run_tests.ps1

So that the test-runner can show the compiler logs (`false` by default).

build: add `-DisableCapture` switch to Windows test-runner

---

CHANGELOG.md
src/backends/sentry_backend_crashpad.cpp

fixes https://github.com/getsentry/sentry-native/issues/1056
When leaving the DSN empty, the crashpad handler wouldn't start. This PR fixes this by warning the user about the empty DSN and not failing the initialization anymore.

fix: don't fail `crashpad` startup on invalid `DSN`

---

src/modulefinder/sentry_modulefinder_linux.c

This is in response to CodeQL security scan alerts 1-3.
`Elf[32|64]_Ehdr[.e_phnum|.e_phentsize|.e_shnum|.e_shentsize]` are all `uint16_t`. This means the loop-var `i` is bounded by `uint16_t` and should fit in a `uint32_t` (to prevent unsigned overflow in the loop). A switch to unsigned still makes sense because we reduce the future chance of unnecessary signed overflow (=UB) in the loop body.
All program/section-header table entry sizes are cast to `uin64_t` even though the multiplication is bound to `uint32_t` by both factors bound by `uint16_t`. This fixes the potential overflow before conversion to the bigger type.

fix: remove a potential overflow before conversion

---

.github/workflows/ci.yml
CONTRIBUTING.md
Makefile
examples/example.c
scripts/git-precommit-hook.sh
src/backends/sentry_backend_crashpad.cpp
src/backends/sentry_backend_inproc.c
src/modulefinder/sentry_modulefinder_apple.c
src/path/sentry_path_windows.c
src/sentry_core.c
src/sentry_core.h
src/sentry_scope.h
src/sentry_string.h
src/sentry_sync.h
tests/requirements.txt
tests/unit/test_sync.c

I've run `make format` as instructed by the contributing.md and linter complained in CI. Later, I've found out it's because of a different version of clang-format so I've added it to .venv so that everyone is on the same version.

chore: add clang-format to venv

---

README.md

as a review result of: https://github.com/getsentry/sentry-docs/pull/11721

docs: clarify macOS support of the `inproc` backend

---

CHANGELOG.md

Fixes an incorrectly set up timeout value when waiting for a `dispatch_semaphore_signal()` from the HTTP-proxy upload task on macOS. See: https://github.com/getsentry/crashpad/pull/111

fix: crashpad_handler proxy-upload semaphore-timeout

---

CHANGELOG.md
include/sentry.h
src/backends/sentry_backend_inproc.c
src/sentry_options.c
src/sentry_options.h
tests/fixtures/dotnet_signal/Program.cs
tests/fixtures/dotnet_signal/crash.c
tests/fixtures/dotnet_signal/test_dotnet.csproj
tests/test_dotnet_signals.py

This is a very early approach to fix https://github.com/getsentry/sentry-native/issues/1026
This is mostly meant for integration in the alpha/beta build sequence of `sentry-native`, `sentry-android`, and `sentry-dotnet` to test against the dotnet-maui on the Android repro project.
_No review is required at this stage, just feedback from the downstream test integration._
cc: @kahest, @bitsandfoxes, @markushi 

feat: introduce optional handler strategy

---

CHANGELOG.md
CMakeLists.txt
external/CMakeLists.txt
src/backends/sentry_backend_breakpad.cpp

Upstream `breakpad` doesn't provide the thread context to the handler callbacks (it does write it to the minidump, though). This change fills the context of the crashed thread and passes it on to the handler callback (which in turn passes it on to the `on_crash` and `before_send` callbacks).
The change keeps compatibility between upstream and our fork in both directions even though this breaks one of the public interfaces:
* our `breakpad` backend in the Native SDK uses the upstream interface if `SENTRY_BREAKPAD_SYSTEM` is defined
* our `breakpad` fork provides the modified interface only if compiled with the Native SDK (i.e., `SENTRY_BACKEND_BREAKPAD` is defined in the `breakpad_client` target).

feat: thread context from breakpad on macos

---

CHANGELOG.md
CMakeLists.txt
cmake/utils.cmake

This should fix the issue raised in #1084.
@dacap, can you give this a try in your setup?

fix: DLL versioning for SDK usage as CMake subdirectory

---

CMakeLists.txt
ndk/README.md
src/sentry_value.c

fixes #1085
It also includes the disabled warnings in the `libunwindstack` submodule (https://github.com/getsentry/libunwindstack-ndk/pull/9) and minor markdown fixes in the `ndk` readme.

fix: warnings in the Android NDK build

---

CHANGELOG.md
ndk/lib/api/sentry-native-ndk.api
ndk/lib/src/main/java/io/sentry/ndk/NdkHandlerStrategy.java
ndk/lib/src/main/java/io/sentry/ndk/NdkOptions.java
ndk/lib/src/main/jni/sentry.c

[Porting the relevant changes from sentry-java 7.x.x](https://github.com/getsentry/sentry-java/pull/3671) to `ndk`, so we'll have the same feature set for upcoming sentry-java 8.x.x

Add options to set NDK handler strategy

---

CHANGELOG.md

fixes https://github.com/getsentry/sentry-native/issues/1064
related to crashpad PR https://github.com/getsentry/crashpad/pull/115

fix(crashpad): add metadata pointer check

---

CHANGELOG.md

chore: rectify changelog link and formatting

---

CHANGELOG.md
include/sentry.h
src/backends/sentry_backend_breakpad.cpp
src/backends/sentry_backend_crashpad.cpp
src/backends/sentry_backend_inproc.c
src/modulefinder/sentry_modulefinder_linux.c
src/path/sentry_path_unix.c
src/path/sentry_path_windows.c
src/sentry_core.c
src/sentry_database.c
src/sentry_envelope.c
src/sentry_logger.c
src/sentry_logger.h
src/sentry_options.c
src/sentry_options.h
src/sentry_sync.c
src/sentry_tracing.c
src/sentry_transport.c
src/transports/sentry_function_transport.c
src/transports/sentry_transport_curl.c
src/transports/sentry_transport_winhttp.c
tests/unit/test_session.c

Fixes https://github.com/getsentry/sentry-native/issues/888
Related to https://github.com/getsentry/sentry-cocoa/issues/4467
The main goal is to allow for outputting just the warnings from `sentry_init`. To accommodate this, we introduce log levels as a way to control what level of output the user gets. We decided against splitting up these levels into `init`-only and global levels, since this doesn't seem like a necessary feature as of yet.

feat: add option to set debug log level

---

.github/workflows/codeql.yml
CHANGELOG.md
README.md

Fixes https://github.com/getsentry/sentry-native/issues/1041 by introducing a fork for the transitive `mini_chromium` dependency. For details: https://github.com/getsentry/crashpad/pull/116.

feat: crashpad support for C++17 compilers.

---

CHANGELOG.md
CMakeLists.txt
examples/example.c
src/modulefinder/sentry_modulefinder_windows.c
src/sentry_os.c
src/symbolizer/sentry_symbolizer_windows.c
toolchains/xbox/CMakeGDKScarlett.cmake
toolchains/xbox/GDK-targets.cmake
toolchains/xbox/gdk_build.props
toolchains/xbox/gdk_build.props.md
toolchains/xbox/gxdk_xs_toolchain.cmake
toolchains/xbox/xbox_build.md

fixes https://github.com/getsentry/sentry-native/issues/1068.

feat: add support for Xbox Series X/S.

---

include/sentry.h

We forgot to remove the note that the sampling context parameter is ignored for `sentry_transaction_start()` in #1108. Mentioned here: https://github.com/getsentry/sentry-native/pull/1108#issuecomment-2591077952

docs: update sampling context parameter description

---

.github/workflows/ci.yml
CHANGELOG.md
CMakeLists.txt
src/sentry_info.c

Fixes: #1115 
Details: https://github.com/getsentry/mini_chromium/pull/2
Tracking PR crashpad: https://github.com/getsentry/crashpad/pull/117

fix: build error introduced by `crashpad` C++17 support

---

src/sentry_core.c

When trying to build the sentry toolchain on windows arm, I am seeing the following warning:
```
1>------ Build started: Project: sentry, Configuration: Debug ARM64 ------
1>sentry_core.c
sentry-native\src\sentry_core.c(404,1): error C2220: the following warning is treated as an error
sentry-native\src\sentry_core.c(404,1): warning C4701: potentially uninitialized local variable 'event_id' used
1>Done building project "sentry.vcxproj" -- FAILED.
```
When we compile the sentry code, we enable warnings as errors globally and hit this warning which fails our builds unless we disable it. It looks like a simple fix. It appears on arm, a separate optimization path is hit and spits out this warning, but it doesn't create the same warning in an x86_64 build. Would like to just get this updated as …

fix: initialize local variable to prevent c4701 warning on windows arm

---

CHANGELOG.md

fixes: #1123
details: https://github.com/getsentry/crashpad/pull/118

fix: support crashpad PAC-stripping on older assemblers.

---

CHANGELOG.md
src/sentry_options.c

fixes: #1121
The implementation allows users to set the environment variable `SENTRY_DEBUG` to `0` to override.

feat: enable debug-option by default in debug-build.

---

CHANGELOG.md
src/sentry_options.c

Fixes https://github.com/getsentry/sentry-native/issues/1131

fix: set default `max_spans` to 1000

---

Makefile
scripts/update_test_discovery.ps1

#1093 recently broke our make/bash/powershell unit-test runner (i.e., the ones not running via `pytest`, which we use in CI) because `clang-format` decided to put the test body on the same line as the test header. Test discovery supports this now 😅 

fix: allow test discovery to handle one-liner unit-tests

---

include/sentry.h

Fixes https://github.com/getsentry/sentry-native/issues/1129

docs: explicitly mention non-null span parent

---

CHANGELOG.md
src/sentry_os.c

This change fixes an issue where the os name on Xbox was being reported as Windows.

Fix Xbox OS name

---

include/sentry.h

docs: improve `sentry_handle_exception()` description

---

tests/unit/sentry_testsupport.h
tests/unit/test_attachments.c
tests/unit/test_basic.c
tests/unit/test_concurrency.c
tests/unit/test_consent.c
tests/unit/test_envelopes.c
tests/unit/test_failures.c
tests/unit/test_logger.c
tests/unit/test_mpack.c
tests/unit/test_options.c
tests/unit/test_path.c
tests/unit/test_sampling.c
tests/unit/test_session.c
tests/unit/test_tracing.c
tests/unit/test_uninit.c

This helps with running unit tests on platforms that need to specify a custom directory to use for writing.
#skip-changelog - purely an internal change

test: add path-prefix for tests that write to FS

---

src/sentry_utils.c

refactor ifdefs for `c_locale()` calls. There was a warning about an unused function

refactor: sentry_utils.c locale()

---

vendor/acutest.h

```
acutest.h:1450:76: error: use of undeclared identifier 'errno'
[build]  1450 |                 fprintf(stderr, "Unable to open '%s': %s\n", arg, strerror(errno));
```
Added the same ifdef as in other code when errno is used

fix: acutest on platforms where `errno` is not defined

---

include/sentry.h

This has been causing confusion. 
More API doc hopefully to help clarify things.

expand on what is sentry_capture_minidump for

---

.github/workflows/ci.yml
README.md
tests/__init__.py
tests/test_integration_crashpad.py

due to [upcoming deprecation](https://github.com/actions/runner-images/issues/11101#issue-2719265843) we update our runners as such:
`ubuntu-22.04 -> ubuntu-24.04`
`ubuntu-20.04 -> ubuntu-22.04`
fixes #1168.

chore: update ubuntu runners

---

CHANGELOG.md
src/modulefinder/sentry_modulefinder_linux.c
src/sentry_core.c
src/sentry_scope.c
src/sentry_sync.h

Potentially fixes #1090 by providing another mutex initializer that manually constructs a recursive mutex instead of relying on a static initialization formula (which either the `pthread` library or we provide).

fix: provide non-static recursive mutex initializer

---

include/sentry.h

The inline docs are no longer correct when handling the data inside the hook events when using the `breakpad` and `crashpad` backend.
Raised here: https://github.com/getsentry/sentry-unreal/issues/817#issuecomment-2713275183

docs: rectify description of hook event handling

---

CHANGELOG.md
CMakeLists.txt
include/sentry.h
src/CMakeLists.txt
src/backends/sentry_backend_breakpad.cpp
src/backends/sentry_backend_crashpad.cpp
src/backends/sentry_backend_inproc.c
src/screenshot/sentry_screenshot.c
src/screenshot/sentry_screenshot_none.c
src/screenshot/sentry_screenshot_windows.c
src/sentry_core.c
src/sentry_envelope.c
src/sentry_envelope.h
src/sentry_options.c
src/sentry_options.h
src/sentry_screenshot.h
tests/fixtures/screenshot/CMakeLists.txt
tests/fixtures/screenshot/screenshot_win32.c
tests/test_integration_screenshot.py

This PR implements #693 for Windows - adds an option for attaching screenshots to fatal error events.
The API is similar to other Sentry SDKs:
```c
sentry_options_t *options = sentry_options_new();
sentry_options_set_attach_screenshot(options, true); // <==
// ...
sentry_init(options);
```
In case of multiple application windows, the screenshot includes all windows belonging to the crashed process and has everything else masked/clipped out:

feat: screenshot capture (windows)

---

.github/workflows/ci.yml
README.md

As they are now [publicly available](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/) we can try and see how far we can get with Native on Linux arm.
Ideally we also have this for Windows, but those runners are [not available yet](https://github.com/orgs/community/discussions/19197#discussioncomment-11946571). 
Related to https://github.com/getsentry/sentry-native/issues/880

chore: add Linux arm64 runner for tests

---

tests/unit/sentry_testsupport.h

Using `Release` configuration on Windows leads to crash in `sentry_test_unit` on `unwinder` test.
```
cmake -B build_vs2019 -T v142  -DSENTRY_BUILD_SHARED_LIBS=OFF -DSENTRY_BUILD_RUNTIMESTATIC=ON -DSENTRY_BACKEND=inproc -DSENTRY_BUILD_TESTS=ON -DSENTRY_BUILD_EXAMPLES=OFF -DCMAKE_SYSTEM_VERSION=10.0 -DCMAKE_POLICY_DEFAULT_CMP0141=NEW -DCMAKE_MSVC_DEBUG_INFORMATION_FORMAT="ProgramDatabase" -DCMAKE_EXE_LINKER_FLAGS_RELEASE="/DEBUG" -DCMAKE_SHARED_LINKER_FLAGS_RELEASE="/DEBUG"
```
```
Exception thrown: read access violation.
uctx was nullptr.
```
```
>	sentry_test_unit.exe!sentry__unwind_stack_dbghelp(void * addr, const sentry_ucontext_s * uctx, void * * ptrs, unsigned __int64 max_frames) Line 46	C
[Inline Frame] sentry_test_unit.exe!unwind_stack(void *) Line 30	C …
```

fix: Improve TEST_VISIBLE macro for Windows - fixes failing unwinder test on Release configuration.

---

CHANGELOG.md
CMakeLists.txt
CONTRIBUTING.md
examples/example.c
include/sentry.h
src/sentry_core.c
src/sentry_options.c
src/sentry_options.h
tests/assertions.py
tests/fixtures/view-hierarchy.json
tests/test_integration_crashpad.py
tests/test_integration_http.py

Closes https://github.com/getsentry/sentry-native/issues/1188

feat: add option to attach view hierarchy

---

src/sentry_core.c
src/sentry_core.h

Switch SDK doesn't provide a custom init - instead, users just call `sentry_init()`. 
This PR enables us to auto-configure custom options and scope (before and after native init, respectively).

feat: allow overriding init on downstream SDKs

---

tests/unit/test_basic.c
tests/unit/test_tracing.c

While preparing another PR (#1204), I've faced an issue that if the downstream SDK sets release in sentry_init(), some tests that match captured envelopes using a custom transport, start failing. The same could be checked by running sentry_test_unit after seetting `SENTRY_RELEASE` env var.
I've tested the changes manually - should I also change tests or CI to test this?

test: fix tests if release is set, e.g. in an env var

---

include/sentry.h
src/sentry_options.c
src/sentry_options.h

This is currently not used on other platforms so I'm adding under the ifdef. 
If we, later, use it elsewhere, we can move it to sentry.h proper.

chore: add send-default-pii setting for NX

---

tests/benchmark.py
tests/conftest.py

Pass pretty-formatted labels to make benchmark charts easier to understand:
| Before | After |
|---|---|
| ![image](https://github.com/user-attachments/assets/df5fc6e7-f73c-4fbd-b7e8-652b833aea5e) | ![image](https://github.com/user-attachments/assets/af7bcad2-050b-4255-8edf-0282d6ff3dca) |

test: use more descriptive benchmark chart labels

---

index.html

By default, every "customSmallerIsBetter" chart is `#ff3838`. Add distinct colors per OS:
- Windows: `#357ec7` (Windows blue)
- macOS: `#717378` (Space gray)
- Linux: `#e95420` (Ubuntu orange)
This makes it easier to visually distinguish between OSes in the benchmark charts.
| Before | After |
|---|---|
| ![image](https://github.com/user-attachments/assets/ac866b2b-7e93-4a9b-a257-9d6bcdb84121) | ![image](https://github.com/user-attachments/assets/f92052b6-2882-436c-a55e-83e9f9c5a165) |
https://github.com/benchmark-action/github-action-benchmark?tab=readme-ov-file#customizing-the-benchmarks-result-page

chore: tweak benchmark charts

---

src/screenshot/sentry_screenshot_windows.c

This PR fixes minor errors when building `sentry-native` for Xbox (see [xbox_build.md](https://github.com/getsentry/sentry-native/blob/f365474360fbe0036910ecd9d2589993544c2507/toolchains/xbox/xbox_build.md) for more details) by excluding Windows-specific code using `_GAMING_XBOX_SCARLETT` platform guard.

Add platform guard to fix Xbox build issues

---

Makefile

Sort `tests/unit/tests.inc` in the same order regardless of the system locale to avoid undesired changes after running `make test` and others.
```diff
$ LC_ALL=C make update-test-discovery
$ git diff
$ LC_ALL=en_US.utf8 make update-test-discovery
$ git diff
diff --git a/tests/unit/tests.inc b/tests/unit/tests.inc
index 3b1c3dc..49fe498 100644
--- a/tests/unit/tests.inc
+++ b/tests/unit/tests.inc
@@ -28,8 +28,8 @@ XX(child_spans_ts)
XX(concurrent_init)
XX(concurrent_uninit)
XX(count_sampled_events)
-XX(crash_marker)
XX(crashed_last_run)
+XX(crash_marker)
XX(custom_logger)
XX(discarding_before_send)
XX(distributed_headers)
@@ -43,8 +43,8 @@ XX(dsn_auth_header_null_dsn)
XX(dsn_parsing_complete)
XX(dsn_parsing_invalid)
XX(dsn_store_url_custom_agent)
-XX(dsn_store_url_with_path) …
```

chore: make update-test-discovery sort locale-independent

---

include/sentry.h
src/CMakeLists.txt
src/path/sentry_path.c
src/path/sentry_path_unix.c
src/sentry_alloc.c
src/sentry_core.c
src/sentry_core.h
src/sentry_database.c
src/sentry_json.c
src/sentry_logger.c
src/sentry_os.c
src/sentry_scope.c
src/sentry_utils.c
src/sentry_utils.h
tests/unit/test_basic.c
tests/unit/test_fuzzfailures.c
tests/unit/test_modulefinder.c
tests/unit/test_mpack.c
tests/unit/test_path.c
tests/unit/test_symbolizer.c
tests/unit/test_unwinder.c
tests/unit/test_utils.c
tests/unit/test_value.c
vendor/acutest.h

Enables a private sentry-playstation SDK to build for PlayStation. I'll follow up with test updates in another PR once I get them to run on PS (or update this one if it's still not reviewed)
#skip-changelog because it's only used internally.

chore: PS downstream SDK support

---

.github/workflows/ci.yml

This change is primarily motivated by the failing codecov invocation in the Linux ARM64 llvm-cov CI config (it works in all other configs, besides `clang-cl`, but this is another issue).
This seemingly was fixed in major 5 of the codecov-action: https://github.com/codecov/codecov-action/issues/1554
codecov works for the first time since you introduced the build config: https://github.com/getsentry/sentry-native/actions/runs/15024781906/job/42222733350?pr=1242#step:23:62

chore: bump codecov-action to 5.4.2

---

CHANGELOG.md
CONTRIBUTING.md
examples/example.c
include/sentry.h
src/sentry_core.c
src/sentry_options.c
src/sentry_options.h
tests/test_integration_http.py

Fixes https://github.com/getsentry/sentry-native/issues/1214 (and related to https://github.com/getsentry/sentry-native/issues/864#issuecomment-1649461251)
ToDo
- Why do we have invoke_before_send passed into prepare_event ([see code](https://github.com/getsentry/sentry-native/blob/e511a8ed0be28e4fd9826854032df370ac0acd77/src/sentry_core.c#L554-L555)), and why is it true for sentry_core occurrences ([1](https://github.com/getsentry/sentry-native/blob/e511a8ed0be28e4fd9826854032df370ac0acd77/src/sentry_core.c#L466), [2](https://github.com/getsentry/sentry-native/blob/e511a8ed0be28e4fd9826854032df370ac0acd77/src/sentry_core.cL1407-L1408)), but passed as !options->on_crash_func for [breakpad](https://github.com/getsentry/sentry-native/blob/e511a8ed0be28e4fd9826854032df370ac0acd77/src/backends …

feat: Add `before_send_transaction`

---

.vscode/extensions.json

see: https://github.com/twxs/vs.language.cmake/issues/119
CMake Tools also recommends uninstalling `twxs.cmake` when installing it. This is an unnecessary dev-setup prologue.

chore: remove `twxs.cmake` from the recommended VSCode extensions

---

src/sentry_alloc.c

This is required in signal handlers due to missing malloc.
#skip-changelog because this is for internal use only

fix: use custom page allocator on ps5

---

.github/workflows/ci.yml

The behavior described in #1263 leads back to a [recent version of `kcov`](https://github.com/SimonKagstrom/kcov/commit/0ecc2dc754765f77c72e2637a244c579d3c63cf2) integrating a `git` metadata collection for the `coveralls` writer.
Our test execution happens in temporary directories rather than a `git` repository, so that all invocations will fail. Additionally, we don't use `coveralls` as a coverage service, but `kcov` doesn't allow selecting its writers (they are all registered on startup). 
Since it is generally a good idea to pin CI dependencies, I think this is a sane fix to flooding the `kcov` jobs with irrelevant `git` errors.
An upstream solution to the problem would be to silence `stderr` on the `git` invocations.

ci: pin kcov to v43

---

CMakeLists.txt
src/CMakeLists.txt

Similar to a custom backend that's already supported, this adds support for downstream SDKs (e.g. PlayStation) to implement custom transport with proprietary APIs of the target platform.
#skip-changelog - this is intended for internal use

feat: allow PS SDK to implement custom transport

---

CHANGELOG.md
include/sentry.h

Required `crashpad `changes: https://github.com/getsentry/crashpad/pull/126
----
* Set up Docker for Windows so you can run Windows containers (follow [these steps](https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#install-the-container-runtime))
* Verify that everything worked by [running a test container](https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/run-your-first-container#run-a-windows-container). If you use the `nanoserver`, as suggested, you will be able to reuse it below.
* Build the Native SDK on the host system as a static build with static runtime libraries. This is extremely helpful when deploying to a minimal image, such as `nanoserver`, given the relatively complex SDK and runtime …

feat: `crashpad_wait_for_upload` Windows support

---

CHANGELOG.md
include/sentry.h
src/sentry_attachment.c
src/sentry_attachment.h
tests/unit/test_attachments.c
tests/unit/tests.inc

A small follow-up to #1266 to support specifying the content type for attachments, as needed for [sentry-unreal](https://github.com/getsentry/sentry-unreal/blob/main/plugin-dev/Source/Sentry/Public/SentryAttachment.h).

feat: add sentry_attachment_set_content_type()

---

.github/workflows/ci.yml

Bump kcov to an un unreleased revision that contains both:
- https://github.com/SimonKagstrom/kcov/pull/482
- https://github.com/SimonKagstrom/kcov/pull/483
Linux (clang 19 + kcov):
| Before | After |
|---|---|
| [47m 18s](https://github.com/getsentry/sentry-native/actions/runs/15874686952/job/44759360055#logs) | [8m 12s](https://github.com/getsentry/sentry-native/actions/runs/15971824656/job/45044951744#logs) |
<details><summary>old details</summary>
When running the very first sentry-native unit test `assert_sdk_name`:
```sh
perf record -g -- kcov --include-path=/path/to/sentry-native/src /tmp/pytest-of-jpnurmi/pytest-20/cmake0/coverage ./sentry_test_unit --no-summary assert_sdk_name
```
It takes roughly 5.5 seconds, and 92% of the time is spent in …

ci: update kcov

---

.github/workflows/ci.yml

The `libsentry.so` and `libsentry-android.so` files where not uploaded to the git release sha, causing craft to be unable to find and upload those symbols to our symbol server.

fix(ci): Fix missing debug symbols for craft

---

tests/valgrind.txt

(potential) successor of https://github.com/getsentry/sentry-native/pull/1323 ; we might be too strict on the `valgrind.txt` suppression stacktrace, so adding wildcards (`...`) might fix the flakiness.
fixes https://github.com/getsentry/sentry-native/issues/1322
<details>
<summary>Explanation (from comment on original issue)</summary>
I wonder if the issue is that the stacktrace doesn't look exactly as specified in [valgrind.txt](https://github.com/getsentry/sentry-native/blob/master/tests/valgrind.txt#L30-L37), but there's some frames in-between:
```
{
pthread stack possibly lost in test_task_queue
Memcheck:Leak
fun:calloc
fun:pthread_create*
fun:sentry__bgworker_start
fun:test_sentry_task_queue
}
```
vs
```
calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
calloc …
```

fix(test): suppress valgrind for SENTRY_TEST(task_queue) 

---

tests/unit/test_concurrency.c
tests/unit/test_sync.c

With the tsan introduction, we also introduced mutexes into the unit tests to properly synchronize some of the test-runners (e.g., acutest has internals that are not thread-safe, for instance, updating records of check results until the test finishes). Sadly, I forgot to cover dynamic mutexes in the two test modules, which are currently not integrated in CI.
This PR only provides fixes for the failing downstream builds. However, we can restructure the mutex setup to eliminate the need to cover dynamic mutex initialization, thereby avoiding a separate test path for mutex initialization.
Raised here: https://github.com/getsentry/sentry-native/pull/1309#issuecomment-3173578709

fix: correctly apply dynamic mutex initialization in unit-tests

---

include/sentry.h

chore: fix `sentry_close` return value documentation

---

.github/workflows/ci.yml

This bump includes a PR I did a while ago upstream: https://github.com/SimonKagstrom/kcov/pull/484.
This eliminates deprecation warnings related to the `curl` MIME API in CI.

ci: bump kcov

---

tests/test_unit.py
tests/unit/test_logger.c

Logger unit tests are always written from a single-threaded perspective. As such, they should be running inside the transport-based test suite since the transport could be concurrently logging and thus would lead to flaky test assertions.

tests: remove flaky logger test from transport suite

---

CHANGELOG.md
cmake/utils.cmake

fix: make windows resource generation multi-config aware
